### ISSUE TITLE
0.6-RC1 bugs

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#109]
This is a meta-issue to keep track of the testing results of the first release candidate (https://github.com/nextcloud/mail/releases/tag/v0.6.0-RC1).

ref https://help.nextcloud.com/t/mail-0-6-rc1-ready-for-testing/3503/1

**Comment by ChristophWurst** [comment]
@plastikschnitzer could you please post your test results here? Thanks :-)

**Comment by ChristophWurst** [comment]
also @nextcloud/mail please update to the RC and give it a test run

**Comment by ChristophWurst** [comment]
(unconfirmed) autoconfig has issues with some providers. cc @Gomez @matiasdelellis

**Comment by ChristophWurst** [comment]
Minor, won't fix in this release:

* Navigation from account settings to new message composer is impossible #10

**Comment by pierreozoux** [comment]
Now we are speaking about autoconfig, never managed to make it working (It is working in Thunderbird though).

**Comment by plastikschnitzer** [comment]
Dear all,
I am following and using this app since version 0.2 and I really love to see the progress because I think cloud is not just about files, its also about mails – many informations are and will always be exchanged by mail and mails are just everywhere (like it or not ;-) ) – to have it right in the cloud is great, I really like to contribute here.

I tested Mail 0.6.0 on NextCloud 10 with multiple mailboxes set up. I use Kubuntu 16.04.1 with Firefox 48 to access the Cloud. 

I am commenting right below the release notes issue list:

> - Alias support
>   [#1523](https://github.com/owncloud/mail/pull/1523) @tahaalibra


Setting up mail alias works, also sending email with this alias. (great feature!!!)
If you add an alias and want to click on "new message" is not possible. All mailbox links below are working. (I think @ChristophWurst mentioned it above)

> - New incoming messages are prefetched
>   [#1631](https://github.com/owncloud/mail/pull/1631) @ChristophWurst

Seems to work, but not always on my side. I can not reconstruct it to 100%, sometimes mails appear immediately by switching in between accounts or folders, sometimes they are loaded again. Problem: If I delete a message, it seems to remain in cache sometimes and this will result in an error message, if it is the first message in a list of mails.

> - Custom app folder support
>   [#1627](https://github.com/owncloud/mail/pull/1627) @juliushaertl

Not tested.

> - Improved search
>   [#1609](https://github.com/owncloud/mail/pull/1609) @ChristophWurst

Working fine, great feature! To be honest, before reading this, I did not even realize, that this is the search function for mails, I always thought its for files because its just the "default search" I knew from the files app...

> - Scroll to refresh
>   [#1595](https://github.com/owncloud/mail/pull/1593) @ChristophWurst

Sroll to refresh works in folders, but not in the folder "all inboxes". Another problem: if the refresh is still in progress and you are scrolling down the list of mails and the request finishes, the list jumps up again to the top of the list of emails


> - Shortcuts to star and mark messages as unread
>   [#1590](https://github.com/owncloud/mail/pull/1590) @ChristophWurst

Working fine.

> - Shortcuts to select previous/next messsage
>   [#1557](https://github.com/owncloud/mail/pull/1557) @ChristophWurst

Working fine.

>
> ## Changed
> - Minimum server is Nextcloud 10/ownCloud 9.1
>   [#84](https://github.com/nextcloud/mail/pull/84) @ChristophWurst

Lets see if there will be users complaining about this step :-D

> - Use session storage instead of local storage for client-side cache
>   [#1612](https://github.com/owncloud/mail/pull/1612) @ChristophWurst

Not tested. 

> - When deleting the current message, the next one is selected immediatelly
>   [#1585](https://github.com/owncloud/mail/pull/1585) @ChristophWurst

Working fine.


> - Client error while composing a new message
>   [#1609](https://github.com/owncloud/mail/pull/1609) @ChristophWurst

I am not sure what is meant here, the link is heading to the search issue?!

> - Delay app start until page has finished loading
>   [#1634](https://github.com/owncloud/mail/pull/1634) @ChristophWurst

I can not test this as I did not see the bug

> - Auto-redirection of HTML mail links
>   [#1603](https://github.com/owncloud/mail/pull/1603) @ChristophWurst

working fine!

> - Update folder counters when reading/deleting messages
>   [#1585](https://github.com/owncloud/mail/pull/1585)

If I read unread emails the count beside the folder goes down (yeah!), but this does not happen with the "all inboxes" folder.

If there are new mails received, the number of unread emails is not rising without a mail app reload.


****************************************************
**Other observations:**

1. Save an email attachment to the cloud -> click on download file while this saving process -> saving process is killed.

2. If I add a new account to the existing ones, the app loads forever and nothing is happening. If I reaload the mail app, the new account shows up.

3. Here one error log which came up after testing, but I know this message also from previous mail app versions:

`Error 	index 	Exception: {"Exception":"TypeError","Message":"Argument 1 passed to OCA\\Mail\\Model\\IMAPMessage::hordeToAssoc() must be an instance of Horde_Mail_Rfc822_Address, instance of Horde_Mail_Rfc822_Group given, called in \/usr\/local\/www\/apache24\/noexec\/cloud\/apps\/mail\/lib\/model\/convertaddresses.php on line 74","Code":0,"Trace":"#0 \/usr\/local\/www\/apache24\/noexec\/cloud\/apps\/mail\/lib\/model\/convertaddresses.php(74): OCA\\Mail\\Model\\IMAPMessage->hordeToAssoc(Object(Horde_Mail_Rfc822_Group))\n#1 \/usr\/local\/www\/apache24\/noexec\/cloud\/apps\/mail\/lib\/model\/imapmessage.php(216): OCA\\Mail\\Model\\IMAPMessage->convertAddressList(Object(Horde_Mail_Rfc822_List))\n#2 \/usr\/local\/www\/apache24\/noexec\/cloud\/apps\/mail\/lib\/model\/imapmessage.php(485): OCA\\Mail\\Model\\IMAPMessage->getToList(true)\n#3 \/usr\/local\/www\/apache24\/noexec\/cloud\/apps\/mail\/lib\/mailbox.php(190): OCA\\Mail\\Model\\IMAPMessage->getListArray()\n#4 \/usr\/local\/www\/apache24\/noexec\/cloud\/apps\/mail\/lib\/controller\/messagescontroller.php(137): OCA\\Mail\\Mailbox->getMessages(0, 21, '')\n#5 [internal function]: OCA\\Mail\\Controller\\MessagesController->index(10, 'VHJhc2g=', 0, 20, '', NULL)\n#6 \/usr\/local\/www\/apache24\/noexec\/cloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php(160): call_user_func_array(Array, Array)\n#7 \/usr\/local\/www\/apache24\/noexec\/cloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php(90): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\Mail\\Controller\\MessagesController), 'index')\n#8 \/usr\/local\/www\/apache24\/noexec\/cloud\/lib\/private\/AppFramework\/App.php(111): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Mail\\Controller\\MessagesController), 'index')\n#9 \/usr\/local\/www\/apache24\/noexec\/cloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php(47): OC\\AppFramework\\App::main('OCA\\\\Mail\\\\Contro...', 'index', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#10 [internal function]: OC\\AppFramework\\Routing\\RouteActionHandler->__invoke(Array)\n#11 \/usr\/local\/www\/apache24\/noexec\/cloud\/lib\/private\/Route\/Router.php(293): call_user_func(Object(OC\\AppFramework\\Routing\\RouteActionHandler), Array)\n#12 \/usr\/local\/www\/apache24\/noexec\/cloud\/lib\/base.php(967): OC\\Route\\Router->match('\/apps\/mail\/acco...')\n#13 \/usr\/local\/www\/apache24\/noexec\/cloud\/index.php(48): OC::handleRequest()\n#14 {main}","File":"\/usr\/local\/www\/apache24\/noexec\/cloud\/apps\/mail\/lib\/model\/convertaddresses.php","Line":34}`

Thats it from my side, happy mailing and happy syncing ;-)

I will also try on ownCloud 9.1. soon.

**Comment by ChristophWurst** [comment]
> Save an email attachment to the cloud -> click on download file while this saving process -> saving process is killed.

I suspect firefox is trying to establish a new connection, which kills all existing ones. I guess we'd have to trigger the download in a new tab to prevent those interruptions.

**Comment by ChristophWurst** [comment]
> Sroll to refresh works in folders, but not in the folder "all inboxes". Another problem: if the refresh is still in progress and you are scrolling down the list of mails and the request finishes, the list jumps up again to the top of the list of emails

Which spinners do you see when that happens? When loading *more* messages, we show the bottom spinner. If we *reload*, we show the top spinner. Maybe you're also seeing the bug I described here https://github.com/nextcloud/mail/issues/113. There both spinners are shown because the logic is kind of confused about what the user wants to achieve by scrolling :-/

**Comment by ChristophWurst** [comment]
> Here one error log which came up after testing, but I know this message also from previous mail app versions:

Known, but not yet fixed bug https://github.com/nextcloud/mail/issues/53#issuecomment-246745664

**Comment by ChristophWurst** [comment]
> If I add a new account to the existing ones, the app loads forever and nothing is happening. If I reaload the mail app, the new account shows up.

This should definitely not happen. Could you please check your browser's js console for any reported errors?

**Comment by plastikschnitzer** [comment]
> Which spinners do you see when that happens? When loading more messages, we show the bottom spinner. If we reload, we show the top spinner. Maybe you're also seeing the bug I described here #113. There both spinners are shown because the logic is kind of confused about what the user wants to achieve by scrolling :-/

The request shown by the top spinner causes the problem. If I am on top of a list and I start scrolling down, the top spinner appears and as soon as the request has been finished, the list jumps back to the beginning. Very annoying if you are reading through the list of emails....
If you are at the end of a list and the bottom spinner request is working, the position in the list is fine!
Not sure if you are describing the same thing in #113 

By the way: Load more emails on scroll in the "all inboxes" folder is working now. No idea why it was not at my initial test... :-/

**Comment by plastikschnitzer** [comment]
`This should definitely not happen. Could you please check your browser's js console for any reported errors?`

The js console is empty. While this request, no js file is loaded and the script console shows nothing. After a few minutes I see somethimes an error like "something went wrong, will reload in 5 seconds" (or similar) and then with the page reload, everything is working fine. The NC error log is empty.

**Comment by plastikschnitzer** [comment]
Short note about ownCloud: Tested in 9.1.0 – seems to work.
