### ISSUE TITLE
Account settings

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#1399]
Leftover from https://github.com/nextcloud/mail/projects/4

**Comment by kevgathuku** [comment]
Hi @ChristophWurst hope you've been good and enjoyed your holidays!
I've got some time on my hands and I would like to work on the account settings page. 

However, I noticed your comment on https://github.com/nextcloud/mail/pull/1350
> With the exception of the account settings (which, frankly, were pretty much unusable before)

My initial thoughts are to re-implement the page as it was before then continue making changes to it gradually. What do you think about this approach?

Otherwise we could agree on what changes need to be made to the original account settings page before re-implementing it.

**Comment by ChristophWurst** [comment]
Hey, happy new year :fireworks:

Great to hear you'd like to help with this. You're right, we can also start with a re-implementation of the old settings and then improve on that. It really doesn't make much of a difference.

The essential settings we have to revive are the general IMAP/SMTP ones. Anything else will be added later. Once with have more than IMAP/SMTP it will make sense to have some kind of tabs to separate these settings. Or some kind of sections with subheaders and such.

**Comment by kevgathuku** [comment]
Progress update on this:

I started on this a while back and have some Work In Progress on https://github.com/nextcloud/mail/tree/feature/account-settings

Unfortunately, I haven't had enough time lately to continue working on it. 
Hopefully I can get some time in the future to finish it up, but I'm just mentioning it here in case anyone would like to pick it up before then.

**Comment by ChristophWurst** [comment]
What a coincidence, I wanted to work on this today :) Is it okay if I take your branch and try to finish it?

**Comment by kevgathuku** [comment]
That's totally cool @ChristophWurst	👍 
A nice coincidence indeed 😃
