### ISSUE TITLE
Ability to add people to Contacts

### ISSUE THREAD

**Issue by HLFH** [nextcloud/mail#143]
> There should be the possibility to add any sender or recipient to your contacts.
> 
> When it’s the sender, we could also take into account the signature of the mail and extract any info like phone numbers or addresses there.

As @jancborchardt said it in the old archived issue: https://github.com/owncloudarchive/mail/issues/363

**Comment by ChristophWurst** [comment]
My current idea (did not find the time to implement yet) for the *sending a message/reply user interaction*:

1. While sending the message (and possibly uploading attachments) we show a nice loading view (spinner + text).
2. Depends on the sent status
    1. If sending fails, we show a error view with details and how to solve it as far as we can. E.g. retry, retry later/save as draft
    2. if sending succeeds, we show a success page, e.g. "You're message was sent successfully :-)"¹ and asking the user if they would like to add the recipient to their contacts.

Another place we should offer an import functionality is in the message detail view (viewing a message of a mailbox). There it should be possible to import any senders/recipients (from, to, cc, bcc fields).

cc @jancborchardt @skjnldsv

¹ with random smileys, of course 💃

**Comment by ChristophWurst** [comment]
Hey there,

I'd just like to let you know that due to the [ongoing issue with Bountysource](https://help.nextcloud.com/t/dont-use-bountysource-anymore/84943) we're discussing ways to move to a different platform. As it looks right now, Bountysource might claim some of the money that was contributed by the community. We will try our best to prevent that. Historically we – the Nextcloud GmbH employees – simply put the claimed bounties back to other tickets until one was solved by a community member. So the money was always *from the community* and *for the community*. We'll therefore move to a better platform and currently don't post any new bounties until this situation is resolved. The current goal is to move/donate the money to [Nextcloud include](https://nextcloud.com/include/) but details will follow in the [forum post](https://help.nextcloud.com/t/dont-use-bountysource-anymore/84943).

Hope this makes sense. If you have any questions please ask them on the forum. This comment will be copy-pasted to all open issues with bounties.

Christoph and the Mail team

**Comment by HLFH** [comment]
Besides forum post, see main GitHub discussion about BS here: https://github.com/nextcloud/mail/issues/44#issuecomment-645487878.

**Comment by jancborchardt** [comment]
This was implemented with the menu when you click on the people in the sender/recipient list up top:
![image](https://user-images.githubusercontent.com/925062/154251214-d3df5518-8469-4ab4-98bb-9608d5de060f.png)
