### ISSUE TITLE
Archiving, moving messages, spam/unspam flagging

### ISSUE THREAD

**Issue by Quix0r** [nextcloud/mail#15]
Some common features such as moving messages (generic) or archiving them (with configuration how to do so: Archives/YYYY/MM/ e.g. or Archives/YYYY-MM/ or Archives/YYYY/ only) and flagging messages as spam or ham (not spam) would be very helpful.

Edit: These features are related but not the same, maybe split them up into 3 separate tickets?

**Comment by jancborchardt** [comment]
Good points, yes. It’s planned, we just don’t have the issues opened yet cause we recently moved repositories.

About the archiving: This will simply be done by using the special-use Archive folder. No further structure is necessary since mails have a date.

(Oh and in the future yes, please do open separate issues about separate things. :)

**Comment by Quix0r** [comment]
I create now separate tickets.
