### ISSUE TITLE
Password security issues discussion again

### ISSUE THREAD

**Issue by andreas-p** [nextcloud/mail#1536]
This actually is a reopen of https://github.com/nextcloud/mail/issues/266 to remind that there's still an unsolved security issue in the mail app. As long as passwords aren't stored in a secure manner, I can't deploy the mail app.

**Comment by ChristophWurst** [comment]
Any ideas for a solution?

**Comment by andreas-p** [comment]
There were suggestions in #266 : the current user's password should be used for encryption, maybe utilizing the passwords app.

**Comment by Heracles31** [comment]
Hi Andreas-p,

There is no miracle here...

For the Nextcloud server to be able to log in an IMAP server, it must have the user's password in clear text or at least, in a format re-usable as is and accepted by the IMAP server.

The Nextcloud server either can do it all by itself or not. If it can do it all by itself, a security incident in that server can recover every IMAP passwords instantly. If the server requires some input from the client, the IMAP passwords will be recovered one at a time, every time a user logs in and access his mailbox. Considering security incidents like this are often discovered long time after they started, the potential end result is about the same.

This requirement for a clear text password is a residual risk of IMAP, not Nextcloud nor the mail app.

If that residual risk is too high for you, then you will need to find another channel to access your e-mail. No matter how you design the system, at the end, either the Nextcloud server can access all the credentials by itself or with the help of the user.

Here, who is it that you don't trust ?
The sysadmin of the operating system ? (or fear a complete root-ing of your box)
Then Zero Knowledge (end-to-end encryption) is your only protection and that is incompatible with an IMAP client sitting between your browser and a mail server.

You do not trust the Nextcloud Daemon ? (or fear an intrusion at application-level only)
Then you can protect yourself by transferring knowledge and control for the credentials to a different ID that will be managed by a separate admin. Still, you will have to trust that other admin instead of the first one, so is it that much better ?

Here, I acknowledged that should my Nextcloud daemon be compromised, the intruder will get all my data. He will not be able to destroy it and I will be able to recover but still, he will access whatever he wishes. The reason is that my Nextcloud is configured in a Docker, running a GR-Sec Linux kernel, in a DMZ and files are managed by a FreeNAS server from another DMZ. Also, Nextcloud can not reach the snapshots, so even a completely root-ed box can not deleted them. The guy will need to root the FreeNAS also. It wlll be much harder and it is up to me to catch the guy before he can succeed.

Nice to talk with you,

**Comment by andreas-p** [comment]
Heracles31, you're completely missing the point.
It's not how NC communicates the password to the IMAP server, it is how it is stored in the account settings.
Since #266, the default mail account was introduced, which will re-use the login password, so it doesn't need to be stored anywhere, which is the safest possible storage.
For additional accounts, the password is stored encrypted in oc_mail_accounts, using credentials derived from config.php settings. With access to the NC server, you have ALL passwords available. This is even worse than all those databases using a weak hash, which require at least some effort to break.

**Comment by Heracles31** [comment]
One way to communicate with someone is to re-use his own words. So...

Andreas-P,

You are completely missing the point. It is not how NC can store IMAP passwords. It is how to prevent someone abusing the NC deamon to recover these passwords.

Once someone can abuse the NC deamon, he will be able to recover all IMAP passwords. The question is, will all of them be recovered at once, or over time, few at a time. As of now, they can all be recovered at once.

By design of IMAP and the hard requirement for NC to access IMAP passwords in clear text, password recovery from NC will always be possible.

Because intrusion as total as that one often last for long period, it is reasonable to consider the intruder will have all the time he needs to recover all the IMAP passwords anyway.

Also, once such a total compromise of your NC deamon happened, do you really think that the IMAP settings is your worst loss ?

You have to trust the NC deamon or acknowledge that the day an incident happen, ALL data handled by NC is potentially compromised. If you are not ready for that, End-to-End encryption (AKA Zero-Knowledge) is your only option. There is such a module in NC, but it is still experimental.

So untill all of your data in NC are protected by the End-To-End encryption module, what you are after is an illusion of security more than actual security.

**Comment by andreas-p** [comment]
Any server is required to store user passwords in a way that makes it impossible to restore the plaintext without brute force. Encrypting the password with a well-known secret from config.pnp is not encryption but obfuscation.

**Comment by Heracles31** [comment]
Hi again Andreas-P,

You said that "any server is required to store user passwords in a way that makes it impossible to restore the plaintext without brute force",

Here, IMAP makes this impossible. The remote IMAP server can receive only clear text passwords and nothing else. Because of that, NC must have access to that clear text password. Even should NC not store anything and asks the user for the password everytime, it will end up handling that password in clear text so a compromised deamon will be able to extract it.

If a password is to be validated locally, then it is possible to store it using one-way crypto and ensure it is not recoverable without brute force. The problem with IMAP is that the password is not to be validated locally but submitted clear text to a remote server.

By using the mail app, you are asking Nextcloud to usurpate your identity towards the IMAP server. You are asking the Nextcloud deamon to connect itself to that IMAP under your identity, retrieve your e-mails and present it to you. So Nextcloud must be able to usurpate your identity, so anyone abusing Nextcloud will be able to usurpate your identity.

What you describe about using the user's main password to encrypt (so to retrieve also) the IMAP password makes the difference between leaking all passwords at once vs leaking them few at a time. There is a little benefit to use a mechanism that will leak passwords few at a time, but the benefit is not as gigantic as you think.

**Comment by andreas-p** [comment]
The stored passwords need to be encrypted using the user password, very simple. This actually seems to apply to the passwords app as well.
@Heracles31, Please stop flooding this issue with unhelpful comments.

**Comment by Heracles31** [comment]
The unhelpful one is the one who just repeat without explaining, without considering other options and for a end result that remains the same. I would say that matches you million time more than anyone else.

So here, you are pleading to ensure that IMAP passwords will be stolen only few at a time in case of an incident abusing the NC deamon, thanks to re-using the user's NC password. Sure, to do it one at a time is better than all at once --if the intrusion is detected early--.

Also, in that situation, the intruder will access everything in the NC account and not only the IMAP password.

To evaluate the situation, we can look at the risk level. The risk is a combination of impact and probability. So what is the risk about the mail.app when you consider the global picture : a compromised NC deamon, one case accessing all IMAP passwords at once versus another one accessing them one at a time.
--Probability of incident is the same for both cases.
--Impact for users who connected during the incident is the same.
--The impact of accessing the entire content of the Nextcloud account is higher than the impact of accessing the IMAP password.

So for the user who had their IMAP password stolen, the bigger risk is not related to their IMAP password nor the way that password was saved or stolen.

The risk is different only for users who were not active during the incident.

Again, probability of an incident is the same for them.
Because the NC deamon by itself can access all the files, the content of their account ends up compromised, unless the server enforced server-side encryption or end-to-end encryption.

With End-to-End encryption, the NC deamon can not retrieve the IMAP password in clear text, so can not connect to a remote IMAP server.

We end up with only server-side encryption.

So one solution for the mail app would be to use a config file instead of the database and have this file hidden in the user account. The credential for IMAP would be saved in that file the same way they are saved in the database as of now. Without server-side encryption, the global risk and protection is the same as of now. Should the administrator turns on server-side encryption, then that file would be re-encrypted by that mechanism and that one is linked with the user's password.

That would requires only to move the config from the database to a file like a json. The content would be the very same and its handling would also be done the same way. Without server-side encryption, the residual risk is the same as of today. With server-side encryption, the extra protection to ensure passwords are stolen one at a time is achieved and the mail.app by itself did not need to do anything differently, other than relying on a file instead of the database.

**Comment by ChristophWurst** [comment]
> Since #266, the default mail account was introduced, which will re-use the login password, so it doesn't need to be stored anywhere, which is the safest possible storage.
> For additional accounts, the password is stored encrypted in oc_mail_accounts, using credentials derived from config.php settings. With access to the NC server, you have ALL passwords available. This is even worse than all those databases using a weak hash, which require at least some effort to break.

I have to agree with @Heracles31 here. If someone has access to the Nextcloud server, they can always read the IMAP password because we *have to* know it in plaintext in order to authenticate on the IMAP server. Even if we used the best crypto, an attacker can just inject a single line of code to log the password when the app connects to IMAP.

The only added security would be to use tokens or app passwords for IMAP/SMTP. That, however, is out of scope for this app. If your mail server supports that you can just enter that token or app password in the app and it should just work.

I'm closing this ticket as the discussion seems to be fruitless and there isn't much we can improve here. Even if we didn't store the password on the server at all and we'd ask the user every time, it would go through Nextcloud in plain text for every IMAP/SMTP access and an attacker can just read that if they have access to the server.

**Comment by andreas-p** [comment]
@ChristophWurst , yes this issue was nicely disassembled.
It's no point arguing that you can intercept the password when a user is online, that's the case for every web app if the server is compromised. If you're going down that road, why is the NC password hashed in the first place?

**Comment by ChristophWurst** [comment]
> If you're going down that road, why is the NC password hashed in the first place?

We don't hash, we encrypt. Because someone with access to a a database (dump) cannot read the password that way. You would need database *and* app server access to read it.

**Comment by andreas-p** [comment]
For some minutes, you made my heart pressure rise until I verified that the normal NC password stored in oc_users actually IS hashed, usually with bcrypt which is widely accepted since only brute force or online interception will give plaintext.
With encrypted passwords in oc_mail_accounts, you obviouxly do NOT need access to the database server beyond what the app server already has.

**Comment by ChristophWurst** [comment]
Yeah, Nextcloud login passwords are a different story. But I don't see why they are relevant in this discussion.

No, of course you don't need the database if you have full access the nc. But a db dump alone won't give you the password, as explained.

**Comment by andreas-p** [comment]
You're applying different security requirements on passwords;  hashed NC passwords, are fine securitywise, with other passwords (imap and passwords app) storage is sloppy: just login to the app server, make you table dump and copy it including config.php. Full disclosure within 30 seconds.

**Comment by ChristophWurst** [comment]
This is exactly what I stated above. Anybody having access to the app server has access to the IMAP password. There is no way around that.

**Comment by andreas-p** [comment]
As stated in https://github.com/nextcloud/mail/issues/266#issuecomment-269798001 3 years before, the stored password could be encrypted using the user password which could give the same security level as the NC-user passwords have now.

**Comment by ChristophWurst** [comment]
No, it would not. Because we have to decrypt it in Nextcloud in order to authenticate on IMAP. You can just read the password there.

**Comment by andreas-p** [comment]
We're turning in circles. This issue is not about intercepting traffic while a user is online, but downloading all information at once and dissecting it offline. NC Passwords need brute force, mail password just config.php.
