### ISSUE TITLE
Ask for password

### ISSUE THREAD

**Issue by flowlee** [nextcloud/mail#1677]
Is it possible to ask for the email password every time the Mail app is opened or an account is accessed?

With so many services using email for password recovery or 2 factor authentication it seems like a security risk to combine access to multiple email accounts under just one Nextcloud login.

Thank you!

**Comment by ChristophWurst** [comment]
No, this is not possible.

**Comment by flowlee** [comment]
Could you please elaborate?

Are there usability concerns? Is this not technically possible?

Thank you!

**Comment by ChristophWurst** [comment]
Yes, it would make the usability worse. Technically it should be doable – would you like to code and maintain it?

**Comment by flowlee** [comment]
To not impact usability too much the whole setup process could remain the same, except for maybe an additional option on the account modification page after the account is created, like a checkbox to not save the password. This should of course then ideally remove the stored password.

I'm not sure I'm able to implement this myself, but I'll have a look!

**Comment by ChristophWurst** [comment]
You will want to have a secure storage of the password on the client then. So that it can be sent with all the requests.

**Comment by Heracles31** [comment]
Hi Flowlee,

Indeed, it is not possible. The reason is that the server must re-use the password multiple times during the same Nextcloud session when a user is logged in. Also, the password must be reachable in clear text because it is to be provided clear text to the remote IMAP server at a regular interval to see if new emails came in since last check.

Once the server stores the password in a recoverable form for at least a complete session (which can last for days), there is no more benefits not to save it forever.

Indeed, to access that many mailboxes with a single login can be a risk. For that, you should use two factor authentication to connect to your Nextcloud account.

Remember that e-mail has never been designed for security. As such, never expect too much from it.

**Comment by flowlee** [comment]
Thank you for this detailed explanation. Maybe I am looking for the solution to my security concerns in the wrong place.

Rainloop has an option to not save passwords. I don't know how this works behind the scenes and maybe the password is indeed saved and then checked on first login. Since my problem isn't exactly with password storage but rather with access to mails from a user's perspective without asking for a password these two issues might not be related at all. For this use case Rainloop might be the right solution but it would have been nice to have the better integration of your app.

I'll look into two factor authentication for Nextcloud, that seems like a good enough compromise.

Thanks again!
