### ISSUE TITLE
Grouping of message threads (threading/conversations) [$320]

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#17]
Similar as in Gmail, Apple Mail for iOS, or Facebook private messages or what have you. Read messages in that thread should be compressed & expandable (also like in Gmail and iOS Mail), and inside the thread the sorting should go recent messages on the bottom (because of reading direction, and that’s how comment threads work).

There should be no indentation or crap like that, just timestamp-based sorting. In the future every individual message in the thread could show a »Reply« button on hover to reply to that specific message. But for now I’d just keep it simple like a one-stream comment thread.

For reference:
- [Jamie Zawinski's message threading algorithm](http://www.jwz.org/doc/threading.html)
- ~~[Max Ogden's JS implementation of said algorithm](https://github.com/maxogden/conversationThreading-js)~~
- https://tools.ietf.org/html/rfc5256

![badge](https://api.bountysource.com/badge/issue?issue_id=37463009)

**Comment by sim6** [comment]
Firstly thanks for your work.

Any thread/conversation support is essential to me. I prefer see all related mails on the same page.

**Comment by jancborchardt** [comment]
@sim6 cool you enjoy the app! :) Since you are a developer, would you be interested in contributing a bit? We are an open project and anyone is welcome!

**Comment by adsworth** [comment]
I would love if this thread/conversation view includes all mail regardless of the folder in which it is saved. Outlook (yes I know) does this and I find it really helps me when I get replies in my INBOX. The thread shows all the mails of the conversation regardless of the folder I saved the previous mails to.
The list should also show a link/label of the folder in which the individual mails are.

**Comment by jancborchardt** [comment]
@adsworth yup, agree. Want to contribute to the bounty on this issue? ;) https://www.bountysource.com/issues/37463009-grouping-of-message-threads-threading-conversations cc @sim6 as well.

**Comment by ChristophWurst** [comment]
Just in case anybody wants to work on this: please first write down how you'd implement this. There are many aspects to consider for this feature to work properly. Thanks.

**Comment by nsrosenqvist** [comment]
Any action on this?

**Comment by ChristophWurst** [comment]
No

**Comment by jancborchardt** [comment]
@nsrosenqvist so you are very welcome to contribute! :)

**Comment by PanderMusubi** [comment]
You can add this line at the top of the issue description, it will update itself

    ![badge](https://api.bountysource.com/badge/issue?issue_id=37463009)

and it looks like

![badge](https://api.bountysource.com/badge/issue?issue_id=37463009)

**Comment by alexanderdd** [comment]
can this be added to the "next" milestone please? It says here https://github.com/nextcloud/mail/blob/master/README.md that it is planned for future versions.

(Yes I am aware that this issue is in the "feature parity" project)

**Comment by jancborchardt** [comment]
@alexanderdd the planning is done according to @ChristophWurst’s availability and he’ll plan accordingly. :) Any contribution is always appreciated, be it from yourself, or telling other developers that they can contribute to this, or also donating to make this feature happen: https://www.bountysource.com/issues/37463009-grouping-of-message-threads-threading-conversations

**Comment by thomas-mc-work** [comment]
> ChristophWurst added this to the 0.20.0 milestone

The [CHANGELOG.md](https://github.com/nextcloud/mail/blob/master/CHANGELOG.md#0200---2019-12-04) tells me it wasn't part of version `0.20`. Was that assignment to this milestone a mistake?

Also the next milestone doesn't contain any issues.

**Comment by ChristophWurst** [comment]
Hey Thomas! Please don't take these milestones too serious. I use the mostly to tag things that definitely go into a release, so I don't forget when releasing. At the time I assigned this ticket I thought 0.18 would be the next version, then 0.19 can ship #2064 and 0.20 can ship #2125. But things have turned out to be a bit more complex. We're about to integrate #2064, though, and you're very welcome to [test the previews at your own risk](https://github.com/nextcloud/mail/pull/2064#issuecomment-580175098). With good feedback we can move forward faster. Any help is appreciated :pray:.

Once #2064 is done we can look into #2125 again. Depending on how complex it is, this feature could land in the next few months. Again, the more people we have for testing and development, the faster it goes :v:.

The next milestone has nothing assigned as I don't do much long-term planning of specific releases. I'm an advocate of [RERO](https://en.wikipedia.org/wiki/Release_early,_release_often) and therefore release frequently. Moving things around constantly is a waste of time.

**Comment by ChristophWurst** [comment]
> We're about to integrate #2064, though, and you're very welcome to [test the previews at your own risk](https://github.com/nextcloud/mail/pull/2064#issuecomment-580175098).

Please see https://help.nextcloud.com/t/call-for-testers-mail-v1-3/75825. We'd appreciate if you could help us test the upcoming release :v: 

The sooner we get the next release done, the more time we have to continue threading :pray:

**Comment by ChristophWurst** [comment]
Hey there,

I'd just like to let you know that due to the [ongoing issue with Bountysource](https://help.nextcloud.com/t/dont-use-bountysource-anymore/84943) we're discussing ways to move to a different platform. As it looks right now, Bountysource might claim some of the money that was contributed by the community. We will try our best to prevent that. Historically we – the Nextcloud GmbH employees – simply put the claimed bounties back to other tickets until one was solved by a community member. So the money was always *from the community* and *for the community*. We'll therefore move to a better platform and currently don't post any new bounties until this situation is resolved. The current goal is to move/donate the money to [Nextcloud include](https://nextcloud.com/include/) but details will follow in the [forum post](https://help.nextcloud.com/t/dont-use-bountysource-anymore/84943).

Hope this makes sense. If you have any questions please ask them on the forum. This comment will be copy-pasted to all open issues with bounties.

Christoph and the Mail team

**Comment by HLFH** [comment]
Besides forum post, see main GitHub discussion about BS here: https://github.com/nextcloud/mail/issues/44#issuecomment-645487878.

**Comment by ChristophWurst** [comment]
Since this is a complex feature, I would like to split it a bit so we can cope with the complexity.

0) Change front-end so an opened message is identified by its database ID (and not accountId, folderId, UID)
1) Change database schema so `mail_messages` also have a `parent_message_id` and a `parent_id` and try to populate both on insert. Also try to find any dangling `parent_message_id`s and update those rows.
2) Change front-end so for each opened message you also see the previous message. **But do not de-duplicate inside the message list** because this is complex and deserves a step of its own.
3) Only show each thread once per message list.

**Comment by ChristophWurst** [comment]
Note: I would, for the first implementation, ignore any threading algorithm but the one based on `References` and `In-Reply-To`, simply because that one will cover most cases. We can look into the subject algorithm later, but it won't be as easy. As a step in between we could already populate the database with the *base subject*.

**Comment by ChristophWurst** [comment]
:bookmark: http://kb.mozillazine.org/Stop_threading_by_subject

**Comment by szaimen** [comment]
🎉

**Comment by ChristophWurst** [comment]
Wait it's mostly just the backe-end changes. I did no intend to close this ticket yet :P

**Comment by ChristophWurst** [comment]
We have the full conversation-style view now. The last piece of the puzzle is the collapsing of message of the same thread in the message list and that will be worked on as https://github.com/nextcloud/mail/issues/3652. Hence I'm closing this as (mostly) done :)
