### ISSUE TITLE
endless download of messages

### ISSUE THREAD

**Issue by viruslab1** [nextcloud/mail#1773]
I am trying to enter the sent emails folder - there is an endless download of messages.
Other folders open instantly.
There are also problems with the support of Cyrillic encodings, some folders are displayed as scrawls.

### Mail app
Mail 0.15.1
Mailserver: mail.ru

### Server configuration
sudo docker run -d -p 80:80 nextcloud
Nextcloud 16.0.1

#### Client configuration
Chrome

**Comment by ChristophWurst** [comment]
Hi!

Thank you for your report. It looks like your report is missing some important sections of your [issue template](https://raw.githubusercontent.com/nextcloud/mail/master/.github/ISSUE_TEMPLATE/bug.md). Please complete it so that we get a better understanding of your setup and the problem to be able to fix the issue.

Thank you.
