### ISSUE TITLE
Archiving messages

### ISSUE THREAD

**Issue by Quix0r** [nextcloud/mail#22]
Messages should be archivable by simple clicks:
- This means that the message(s) should be moved to e.g. Archives/YYYY/MM, Archives/YYYY or Archives/YYYY-MM depending on how the user configures it
- Moving in one folder only may make it one day extremely large and a fast pre-selection of messages is not possible (e.g. you know the message came August, 2016, then choose Archives/2016/08/ and start searching there)

Splitted from #15

**Comment by jancborchardt** [comment]
(Just reposting the reply here for the record:)

About the archiving: This will simply be done by using the special-use Archive folder. No further structure is necessary since mails have a date. We should improve that in the search function.

**Comment by Gomez** [comment]
Related to #24

**Comment by milankni** [comment]
For those preferring separate Archive folder at least by year, some mail apps allow to simply set the "Archive" folder.
Not that necessary (I could use the standard "Archive" folder and move its contents once a year to a subfolder), but nice to have.

**Comment by NathanielHill** [comment]
Has any work been done on this?

**Comment by sim6** [comment]
Move it to SPECIAL-USE \Archive folder, without subfolders, is fine for me.

**Comment by denics** [comment]
Dear all, first of all thanks for the great software.
Using the special "archive folder" is a possibility, but this solution occupy space in the IMAP server. Would it be possible to implement a local archive procedure in a folder outside the IMAP server? Maybe in the Nextcloud filesystem? 
I hope I have been clear :D

**Comment by szaimen** [comment]
Any update here? would be nice beeing able to quickly archive mails to clean up the mailbox without having to delete all mails.

**Comment by ChristophWurst** [comment]
Hey there,

I'd just like to let you know that due to the [ongoing issue with Bountysource](https://help.nextcloud.com/t/dont-use-bountysource-anymore/84943) we're discussing ways to move to a different platform. As it looks right now, Bountysource might claim some of the money that was contributed by the community. We will try our best to prevent that. Historically we – the Nextcloud GmbH employees – simply put the claimed bounties back to other tickets until one was solved by a community member. So the money was always *from the community* and *for the community*. We'll therefore move to a better platform and currently don't post any new bounties until this situation is resolved. The current goal is to move/donate the money to [Nextcloud include](https://nextcloud.com/include/) but details will follow in the [forum post](https://help.nextcloud.com/t/dont-use-bountysource-anymore/84943).

Hope this makes sense. If you have any questions please ask them on the forum. This comment will be copy-pasted to all open issues with bounties.

Christoph and the Mail team

**Comment by HLFH** [comment]
Besides forum post, see main GitHub discussion about BS here: https://github.com/nextcloud/mail/issues/44#issuecomment-645487878.

**Comment by JPustkuchen** [comment]
Sorry to jump in here - I'm not sure if we should cover this in a separate topic or see this as sub-topic, but as Nextcloud is used in several (EU) Companies, Revision-proof e-mail archiving is a relevant topic for an all-in-one solution like nextcloud and the area of archiving eMails.

See: https://www.it-recht-kanzlei.de/recht-archivierung-email.html

This could be interesting for (paid) enterprise solutions, but small companies and other users might also benefit from such a solution. Perhaps it would also be worth to have a look at an existing open source solution to integrate / collaborate with like https://www.mailpiler.org
?

Is a general statement from the NextCloud Team possible perhaps? I guess you're suffering from the same topic ;) 
I couldn't find an existing topic on this yet, I'm sorry if it was discussed already.

**Comment by Quix0r** [comment]
This discussing is ongoing since 5 years now. :dancers:

**Comment by yousefamar** [comment]
I asked about this elsewhere and was told this is basically abandoned and that people go for Rainloop instead. Overall, I've given up on any sort of email over nextcloud personally

**Comment by Breitling1992** [comment]
Any update? This would be an amazing addition to Nextcloud, to use it as Mail Archive.

**Comment by matbgn** [comment]
Okay, am I right if I summarize the situation as follows:

6 years, nothing done yet to move with one click a mail to a specific folder. 
> Side notes: Create a folder if not there and possibly map it to a different location similar to Drafts/Sent/Trash

Right?

Is it so huge to achieve it? What will be the key/macro steps looking as a dev perspective? Can someone (preferably a NC tech lead) break it to a fair good first PR (so I could maybe give it a shot in the coming month)?

**Comment by ChristophWurst** [comment]
I would say it needs the following parts
* Add another mailbox picker to the *Default folders*. IMAP does have a special use attribute for the archive mailboxes but to my knowledge it can be multiple. Just like there can be multiple draft mailboxes. So I would prefer a setting to make this deterministic.
* Add an action to a thread -> moves the thread's messages to the configured archive mailbox
  * This could be hidden if no archive mailbox is selected yet
* Add an action to a message -> moves the message to the configured archive mailbox
  * This could be hidden if no archive mailbox is selected yet
* Right now it looks like there is nothing to change on the backend since the operation (move) is already there and not different to moving between any other mailboxes

![Bildschirmfoto vom 2022-05-05 14-24-55](https://user-images.githubusercontent.com/1374172/166922783-b676dfcc-cf96-4135-9b20-2266a928372e.png)

**Comment by matbgn** [comment]
Thanks for your feedback! I'm going to put a TODO to take this in August

What's your rate for a first PR on a scale of 10?

**Comment by rinurinu** [comment]
Hi, I'm new here. Just wanted to mention an archive Button as suggested would be great. Thanks everybody for the great work on nextcloud.

**Comment by matbgn** [comment]
> Thanks for your feedback! I'm going to put a TODO to take this in August
> 
> What's your rate for a first PR on a scale of 10?

Unfortunately due to workload I was not able to address this issue in August... I will postpone it to an unknown date and would be glad, in the meantime, if someone could take it.

**Comment by arjentz** [comment]
> * Add another mailbox picker to the _Default folders_. IMAP does have a special use attribute for the archive mailboxes but to my knowledge it can be multiple. Just like there can be multiple draft mailboxes. So I would prefer a setting to make this deterministic.
> * Add an action to a thread -> moves the thread's messages to the configured archive mailbox
>   
>   * This could be hidden if no archive mailbox is selected yet
> * Add an action to a message -> moves the message to the configured archive mailbox
>   
>   * This could be hidden if no archive mailbox is selected yet
> * Right now it looks like there is nothing to change on the backend since the operation (move) is already there and not different to moving between any other mailboxes

@ChristophWurst Implemented these points in #7355. The only change to the backend is storing the mailbox preference.

**Comment by JPustkuchen** [comment]
@ChristophWurst thank you very much for the cleanup!
Let me ask one last question here, before this issue goes into the archive... ;)

What do you think about the points in my comment: https://github.com/nextcloud/mail/issues/22#issuecomment-913746984
?

Should we create a separate issue for that?
At least for ALL companies in Germany this is an important legal requirement, so it would help many many people and we should at least decide if this will be in scope in the (far) future!

**Comment by jancborchardt** [comment]
@JPustkuchen it would indeed be great if you can open a separate issue for that so it does not get lost, thank you! :)

**Comment by JPustkuchen** [comment]
@jancborchardt sorry I missed that, but @sunjam was so friendly to do it. Thank you!
