### ISSUE TITLE
why reinvent what exists already?

### ISSUE THREAD

**Issue by cptMikky** [nextcloud/mail#2250]
### Question

There are quite a few OSS web-based e-mail clients there, why build a new one from scratch?

#### Summary

I'm honestly curious about the reasons. From my perspective I've been trying this app on-and-off for over a year and I don't really *see* any progress. *See* here means that as a BFU, the client still looks basically the same to me, no new features, no UI updates, etc. Yes, when I check the changelog I see progress but the usability did not subjectively improve at all. I've tried giving this app as an alternative to Rainloop in my Nextcloud instance to actual BFUs and they chose Rainloop unanimously even though some of them did not use either one before. "Weird" and "awkward" were the common denominatoros in feedbacks I got on this app from them.

I have a feeling this is a wasted effort and looking at the changelog I see a lot of fixes that are already solved in other mail clients.

Rainloop, according to the app list, looks like a quite popular choice for Nextclouders - why not fork and integrate that? Instead of reinventing the wheel by creating a rectangle and trying to make it round while there are round enough wheels already... (unintentionally, this also reminds me of RoundCube, another full-featured and stable webmail :) there's also Mailpile, Sogo and others, most of them having years of development behind them).

Please don't take this question wrong, I'm merely curious and by no means I want to implicate you (the devs) are doing a bad job.

**Comment by ChristophWurst** [comment]
Hi,

thank you for your feedback. I see your point when you look at our app from the outside. Let me give you some insights.

What we want to achieve here is a native integration of a mail client in Nextcloud. The goal is not to have yet another web-based client, but to have something as tightly connected with other Nextcloud features as possible.
If we took on the existing solutions, it would be easy to just get it running. But it wouldn't match the general design and feel of Nextcloud. Moreover, they don't really integrate well with other components, see the poor Roundcube app for example. And the existing solutions are all applications, not libraries, hence they aren't designed to be integrated somewhere but just run. There are no hooks, APIs or similar to customize how they render and where to put which information. We could take a snapshot of their code and adjust it to our needs, but that would make it very hard to keep in sync with the upstream changes, especially on a code base written by someone else.

We're not totally reinventing this. A lot of *magic* happens on the communication to IMAP. But for that we use the awesome Horde libraries. So, while we still have to write *some* code, most of the tricky stuff is already there. The majority of server-side logic is about getting data from Horde and passing it to the front-end and integrating with other parts of Nextcloud.

I agree on the progress and that we're still a very basic app. This is mainly due to the little time spent on the development of this app. For the most part, this was my side project, then became something I partly worked on during a part-time job and now eventually I get more and more time to work on this. That is why you might have noticed the steeper progress recently, and, if you look at the Github information, you might also see that big features are already in the pipeline.

Hope this makes things a bit more clear :)
Cheers

**Comment by cptMikky** [comment]
Thanks Christoph, I guess it makes sense from the integration point of view. Thanks for your insights, I think I have a better understanding now.

I'll try testing the app from time to time and give actual feedback :)

**Comment by ChristophWurst** [comment]
> I'll try testing the app from time to time and give actual feedback :)

Thanks :heart: This is highly appreciated!
