### ISSUE TITLE
Quick filter bar

### ISSUE THREAD

**Issue by Rychu-Pawel** [nextcloud/mail#2433]
### Feature Request

I think it would be a cool feature to have a quick filter bar displayed at the top of message pane to quickly filter read / unread / starred / with attachement emails. Maybe searchbar can be moved there too? In my opinion its current position is a bit unintuitive.

**Comment by ChristophWurst** [comment]
> opinion its current position is a bit unintuitive.

It is. And there are discussion about moving it. cc @jancborchardt

**Comment by jancborchardt** [comment]
As the Talk app has the search/filter bar more presently and is doing pretty well with it, we could try it here too.

In combination with https://github.com/nextcloud/server/issues/16934#issuecomment-542201187 what could work is a search icon in the top right of the messages list which on click expands the search bar in the row.

What do you think @ChristophWurst?

**Comment by ChristophWurst** [comment]
Sounds good

**Comment by alexanderdd** [comment]
@Rychu-Pawel can you open a separate issue for the search? The title of this issue is "quick filter bar", so let's focus on that here?! (maybe also move the connected comments there?)

In my workflow it is an absolute necessity to filter by unread/starred. So for me, this has way higher priority than every other issue here, and it's the main reason why I can't use mail app for my emails atm. 

User story: I receive ~20 Emails per day. And there are always some that I want to answer later, so I mark them unread. Without filtering, I need to scroll for a long time to find the unread ones, and I can never be sure if I missed some really old unread ones. Also, I mark important mails with a star. Sometimes I need to filter by starred emails to quickly find an email that I received two or three months ago. Sometimes it is necessary to filter for starred and unread emails, because this returns me this one really important email which I did not answer but it is already a month old so I would never find it by scrolling down in my regular inbox. 

Interface: I think I prefer a "Filter" (word or icon) drop down menu, right above the message list, with checkboxes (so multiple filter combinations can be applied) for unread, starred, has attachment. -  "Filter" word/icon should be red when a filter is active. I can do a mock-up if you want?

Btw what means "Needs triage"?

**Comment by alexanderdd** [comment]
Should I do a mock-up?
