### ISSUE TITLE
Include Attachments And Images In Forwarded Mail

### ISSUE THREAD

**Issue by thomaskonrad** [nextcloud/mail#246]
Apparently, images and attachments are removed from a mail when forwarding it. It would be great to optionally include attachments when forwarding messages. iOS, for example, asks the user whether or not attachments should be included in the forwarded mail. Outlook includes them automatically.

By the way - great Nextcloud app, I love it a lot!

**Comment by ChristophWurst** [comment]
> By the way - great Nextcloud app, I love it a lot!

I'm glad that you like it 🙌 Btw, you can rate the app at https://apps.nextcloud.com/apps/mail ;-)

**Comment by thomaskonrad** [comment]
Done!

**Comment by Detrius** [comment]
I would like to push this request again.
It would be nice if attachments would be forwarded automatically, together with the mail body.

(By the way, I also agree that the Nextcloud app is great :)

**Comment by szaimen** [comment]
Is there any update on this?
I think this is one of the last missing features to be able to use the app productively.
But not only the attachments and images should get forwarded. Also the (HTML-)formatting of the mail that you are answering to or forwarding should be as they are.

**Comment by ChristophWurst** [comment]
> But not only the attachments and images should get forwarded. Also the (HTML-)formatting of the mail that you are answering to or forwarding should be as they are.

That is already the case. Or at least to the degree that *our* editor is capable of working with the HTML. It will strip any unknown formatting, though.

**Comment by szaimen** [comment]
@ChristophWurst Why not preserving all html code despite the formatting is known or not?

**Comment by ChristophWurst** [comment]
How could a WYSIWG editor work with structures it doesn't understand?

**Comment by szaimen** [comment]
Okay, I understand the problem now, but the problem is that in the current state it seems to be a bug when not preserving all the html formatting. Also it seems to strip a LOT of formatting: sometimes I think it just preserves the plain text... e.g. tables aren't supported?

Maybe an idea to fix this:
Why not making the content you are answering to or forwarding read only? Then you could preserve the formatting while beeing able to only use the formatting that the editor uses? I don't know if it is just me, but honestly I never change content in the mails that I answering to or forwarding; of course I should be able to see the content of the mail that I am answering to or forwarding while writing the mail draft also to be able to copy content to the draft...

so something like this:
1. click on forwarding or answering
2. the draft view opens; on the buttom is the mail that you are answering to or forwarding. when scrolling down, you see the whole mail that you are answering to or forwarding and are able to copy content to the draft view above
3. when clicking on "send mail" or if the draft gets saved, the content that you are answering to or forwarding gets attached to the buttom of the draft/mail.
4. when opening the draft again, it strips the content that you are answering to or forwarding for editing and show it again in the read only view below...  and it gets attached to the mail again when saving the draft or sending the mail.

What do you think?

**Comment by szaimen** [comment]
Better would be of course if the editor would support all html formatting. But this is probably not doable. 

Another idea is just disabling the stripping to preserve all (unknown) formatting and show it as plain text. Then at least an editor that is able to understand the formatting can show it again after sending the mail (or showing the draft with another mail app. 

But stripping all unkown html formatting isn't really the best solution IMO.

**Comment by ChristophWurst** [comment]
Hey there,

I'd just like to let you know that due to the [ongoing issue with Bountysource](https://help.nextcloud.com/t/dont-use-bountysource-anymore/84943) we're discussing ways to move to a different platform. As it looks right now, Bountysource might claim some of the money that was contributed by the community. We will try our best to prevent that. Historically we – the Nextcloud GmbH employees – simply put the claimed bounties back to other tickets until one was solved by a community member. So the money was always *from the community* and *for the community*. We'll therefore move to a better platform and currently don't post any new bounties until this situation is resolved. The current goal is to move/donate the money to [Nextcloud include](https://nextcloud.com/include/) but details will follow in the [forum post](https://help.nextcloud.com/t/dont-use-bountysource-anymore/84943).

Hope this makes sense. If you have any questions please ask them on the forum. This comment will be copy-pasted to all open issues with bounties.

Christoph and the Mail team

**Comment by HLFH** [comment]
Besides forum post, see main GitHub discussion about BS here: https://github.com/nextcloud/mail/issues/44#issuecomment-645487878.

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/mail/pull/3950 feature is about to land :rocket:

**Comment by mrAceT** [comment]
**BUMP**

You strip formatting, in the forward.. ok great?
But what is the argument for not including attachments then? I really don't understand.

A mail with attachment often has three parts, marked in the header of the mail with something linke:
`Content-Type: multipart/mixed; boundary="------=_MB0C37B3D4-C11D-xxxxxxxxxxxxxxxxxxxxxxxxx`

then most often first followed with another container with a container for PLAIN text and HTML:

```
--------=_MB0C37B3D4-C11D-xxxxxxxxxxxxxxxxxxxxxxxxx
Content-Type: multipart/related; boundary="------=_MBC3416085-1121-yyyyyyyyyyyyyyyyyyyyyyyyyy"

--------=_MBC3416085-1121-yyyyyyyyyyyyyyyyyyyyyyyyyy
Content-Type: multipart/alternative;
 boundary="------=_MB6037FCE6-59F6-zzzzzzzzzzzzzzzzzzzzzzzzz"

--------=_MB6037FCE6-59F6-zzzzzzzzzzzzzzzzzzzzzzzz
Content-Type: text/plain; charset=utf-8; format=flowed
Content-Transfer-Encoding: quoted-printable
```

there first the PLAIN text mail..

```
--------=_MB6037FCE6-59F6-zzzzzzzzzzzzzzzzzzzzzzzz
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: quoted-printable
```

and the HTML mail

That group is then closed of via:

`--------=_MB6037FCE6-59F6-zzzzzzzzzzzzzzzzzzzzzzzz--`

Do take note of the two 'dashes' at the end!

Then you'll see the "header divider" again mrking the start of the attachments

```
--------=_MBC3416085-1121-xxxxxxxxxxxxxxxxxxxxxxxxx
Content-Type: image/png; name=GGGG.png
Content-Transfer-Encoding: base64
Content-Disposition: inline
Content-Id: <something@blabla>
```

Followed with the base64 encoded attachment

This is repeated for more attachments

All this is ended with:

`--------=_MB0C37B3D4-C11D-xxxxxxxxxxxxxxxxxxxxxxxxx--`

Again  take note of the two dashes at the end here

Honestly, this, in my humble opinion has absolutely nothing to do with formatting of the HTML part?!
And to be completely honest I am somewhat dismayed that something quite essential like this, requested almost 6 years ago isn't functional!

I have a client that needs this functionality, badly. 
There is no plugin, no workaround, not a button somewhere I have mist giving me the option to forward the attachment?

Is it really the only option to save the attachment to file and the forward it?
**(why isn't there, at that option "safe to file", the option "forward this attachment"!?)**

Now I fear I am going to lose this client over this.. the horror..
