### ISSUE TITLE
Sending mail inserts newlines

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#2481]
Write a mail:
```
⏮ Last week:
- More 18 reviews and polishing
- Went through notifications
```

Send it, and see it formatted like this:
```
⏮ Last week:

- More 18 reviews and polishing

- Went through notifications
```

Priority cause it changes mail text unexpectedly. :)

**Comment by ChristophWurst** [comment]
The "problem"

* CKeditor uses paragraphs for <kbd>Enter</kbd> and line breaks for <kbd>Shift</kbd>+<kbd>Enter</kbd>
* Nextcloud changes paragraph styling to be indistinguishable with line breaks
  * This makes paragraphs in the editor look like line breaks
* When you view your sent email you see actual paragraph formatting because the iframe does not use Nextcloud styling

> Priority cause it changes mail text unexpectedly. :)

Yeah, pretty much every bug report is about unexpected behavior :see_no_evil:

**Comment by ChristophWurst** [comment]
Regarding `<p>` vs `<br>` https://github.com/ckeditor/ckeditor5/issues/617

**Comment by jancborchardt** [comment]
> Yeah, pretty much every bug report is about unexpected behavior see_no_evil

Let me say it like this: Priority because it not only is a bug which trips you up, but makes you look like an idiot to people receiving your emails. ;)

**Comment by StCyr** [comment]
Wouldn't it be possible to send Nexcloud's p style together with the email?

Like adding `style="margin:0;"` to all `<p>` tags?

**Comment by Friptick** [comment]
The guy at CKEditor is right, line breaks are the root of all evil, visually and semantically. They must be discouraged at all costs.

**Comment by StCyr** [comment]
Good. Now, what’s the solution to get the emails properly formated?

**Comment by ChristophWurst** [comment]
I'd be fine with a custom styling on the `p`'s right now.

**Comment by jancborchardt** [comment]
Reopening since this still happens – ref @ma12-co if you have additional logs since you ran into that issue recently.

**Comment by ma12-co** [comment]
Yep, still happening as of today on our company instance

**Comment by StCyr** [comment]
Isn't it solved now? @ma12-co ?

**Comment by ma12-co** [comment]
It didn't happen to me recently, but I haven't actively tried to reproduce. Do you need help with that?

**Comment by StCyr** [comment]
> It didn't happen to me recently, but I haven't actively tried to reproduce. Do you need help with that?

Well, at least I don't remember how to reproduce this issue 😞

**Comment by cwx0046** [comment]
How about adding an option that makes `Enter` insert `<p>` tag with mb-0 style:

```javascript
editorConfig: {
    emailMode: true
}
````

```html
<p style="margin-bottom: 0;"></p>
````

**Comment by ChristophWurst** [comment]
emailMode? Is that a feature of CKEditor 5?

**Comment by thstyl2000** [comment]
I am not sure if this is related, but replying to a mail that has visible empty lines, inserts a number of empty lines in the comment, eg

Dear Mr. Hammersmith,

nice to hear from you.

Best,
Your Buddy

becomes

\> Dear Mr. Hammersmith,
\>
\>
\>
\> nice to hear from you.
\>
\>
\>
\> Best,
\> Your Buddy

and the behavior is being iterated after a new reply.

**Comment by kesselb** [comment]
##### 1. The example from the initial post works fine for me.

```
⏮ Last week:
- More 18 reviews and polishing
- Went through notifications
```

##### 2. I'm able to reproduce some "additional" newlines for the following scenario.


| | Alice | Bob |
| --- | --- | --- |
| Writing mode| Rich text | Plain text |


1. Alice is writing an email to Bob like:

![image](https://user-images.githubusercontent.com/3902676/128936052-7e8d108d-3a3e-4e0c-94fe-11f9f749b44f.png)

2. Alice press "Send" and mail (=> horde) create a text version of the html email automatically. 
3. Bob receives an email like below: 

```

--=_CicZB_F1vzK6_wIwg5KtjBU
Content-Type: text/plain; charset=utf-8
Content-Description: Plaintext Version of Message
Content-Transfer-Encoding: 8bit

Hello,

 

a. aa

b. bb

c. cc

d. dd

 

1. a

2. b

3. c

4. d

 
-- 
 

Test123 Test123

 
--=_CicZB_F1vzK6_wIwg5KtjBU
Content-Type: text/html; charset=utf-8
Content-Description: HTML Version of Message

<p style="margin:0;">Hello,</p><p style="margin:0;">&nbsp;</p><p style="margin:0;">a. aa</p><p style="margin:0;">b. bb</p><p style="margin:0;">c. cc</p><p style="margin:0;">d. dd</p><p style="margin:0;">&nbsp;</p><p style="margin:0;">1. a</p><p style="margin:0;">2. b</p><p style="margin:0;">3. c</p><p style="margin:0;">4. d</p><p style="margin:0;">&nbsp;</p><div class="signature">--&nbsp;<p style="margin:0;">&nbsp;</p><p style="margin:0;">Test123 Test123</p><p style="margin:0;">&nbsp;</p></div>
--=_CicZB_F1vzK6_wIwg5KtjBU--
```

The html element `p` is converted to `text text\n\n` here: https://github.com/horde/Text_Filter/blob/0182edd3f762909146196a43dc8da2c872ab8964/lib/Horde/Text/Filter/Html2text.php#L221-L231. I guess we need to overwrite the default behavior here. 

##### 3. A list (created by the editor toolbar) is converted properly. 


https://user-images.githubusercontent.com/3902676/128937349-3ec6df83-0174-41a7-b26a-c67c4ac7f179.mp4

The list itself looks a bit weird (in the rich text editor mode because the numbers are very left) but the plain text versions looks like a proper list.

```
--=_kKDe5X9pIokrgrncwp2xnAt
Content-Type: text/plain; charset=utf-8
Content-Description: Plaintext Version of Message
Content-Transfer-Encoding: 8bit

Hello Hello

 

  * aa
  * bb
  * cc
  * dd

 

 
-- 
 

Test123 Test123

 
--=_kKDe5X9pIokrgrncwp2xnAt
Content-Type: text/html; charset=utf-8
Content-Description: HTML Version of Message

<p style="margin:0;">Hello Hello</p><p style="margin:0;">&nbsp;</p><ol><li>aa</li><li>bb</li><li>cc</li><li>dd</li></ol><p style="margin:0;">&nbsp;</p><p style="margin:0;">&nbsp;</p><div class="signature">--&nbsp;<p style="margin:0;">&nbsp;</p><p style="margin:0;">Test123 Test123</p><p style="margin:0;">&nbsp;</p></div>
--=_kKDe5X9pIokrgrncwp2xnAt--
```
but the `p` (e.g. hello hello) also have additional newlines here.

**Comment by ChristophWurst** [comment]
Fix is at https://github.com/nextcloud/mail/pull/5428
