### ISSUE TITLE
Mirror of all email attachments from Nextcloud mail accounts directly in their Nextcloud files directory

### ISSUE THREAD

**Issue by HLFH** [nextcloud/mail#249]
Hi,

Nextcloud mail should add the feature of creating a mirror of all email attachments from Nextcloud mail accounts directly in their Nextcloud files directory.

There was an extension before: https://github.com/fincluster/owncloud_mail_attachments, but it does not work with Nextcloud and Nextcloud mail.

**Comment by ChristophWurst** [comment]
Hi,

I don't think that we will implement a feature like that in the foreseeable future because it's probably not used by many users. Therefore, I suggest to update that app instead. It's probably not too complicated to fix it for a recent version of Nextcloud. You probably just need to update the info.xml and maybe some of the classes. Let me know if you need any help with that!

**Comment by HLFH** [comment]
Ok :) I will not use Nextcloud mail.

**Comment by janklostermann** [comment]
Hi Christoph,
Could you explain WHY you will not implement such a feature in the foreseeable future?
I am surprised, as I see that a main reason  of existence for a specific nextcloud mail client lies in its integration with the nextcloud server, especially with the file storage. 
Some clarification on that I would heavily appreciate, including what are other "features like that". It could help clarify the Product Goals of the Mail App... (or at least make them more visible.

Thanks for considering it.
Jan


Am 18. Dezember 2016 17:38:34 MEZ, schrieb Christoph Wurst <notifications@github.com>:
>Hi,
>
>I don't think that we will implement a feature like that in the
>foreseeable future because it's probably not used by many users.
>Therefore, I suggest to update that app instead. It's probably not too
>complicated to fix it for a recent version of Nextcloud. You probably
>just need to update the info.xml and maybe some of the classes. Let me
>know if you need any help with that!
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/nextcloud/mail/issues/249#issuecomment-267831294

-- 
Jan Klostermann 
Systemingenieur - Agile Coach - Mediator

Tel: +49 179 46 288 19

Von unterwegs gesendet.

**Comment by ChristophWurst** [comment]
Hi Jan,

> a main reason of existence for a specific nextcloud mail client lies in its integration with the nextcloud server

I totally agree on this point. If we had no integration there would be no sane reason to invest my spare time into this project. However, *we do* work on tight integration: we auto-complete contac email addresses, you can import ics attachments into your calendars and you can save any attachment to Nextcloud's file system. Of course, there is still a lot to do, the next integration I'm planning to realize will be the ability to attach files as Nextcloud share where the recipients get a link instead of an mail attachment.

Almost all of the developers of this app work on it in their spare time. Therefore our resources are limited. Additionally, the app is still in an early state, compared to what a state-of-the-art mail client can do.
> "features like that"

If I understood the OPs feature request correctly, this ticket is about a feature which syncs all account's messages to the Nextcloud file system. First of all, personally, I think this is a rare use case. I don't know why I would benefit from such a feature. On the other hand we currently lack other features, that the majority of users will use, e.g. message threading. Therefore, we set priority on tasks that are more likely to be used than those who are used rarely.

I decided to close this ticket now because from my experience with this project (I've also worked on it when it was developed in the oc community) this kind of ticket won't be implemented in the foreseeable future.

Does that make sense to you? :-)

You are very welcome to help us and implement this feature if you really need this. I'd be happy to give you some pointers to get started. Just let me know and I'll reopen and assign you to this ticket. Thanks.

**Comment by jancborchardt** [comment]
@HLFH @janklostermann we’ll keep the issue open as it’s a good idea for integration. However as Christoph said before it’s not a focus at the moment or in the near future as more important things need to be fixed and developed first (as you can see from the milestones).

You are more than welcome to contribute though, or help bring the attachments app by @fincluster & @prdn back to life for Nextcloud: https://github.com/fincluster/owncloud_mail_attachments :)

**Comment by heaven73** [comment]
Hello @ChristophWurst @jancborchardt,
As new nextcloud user, i think the use of such a feature is underestimated.
I would like to make an example scenario: incoming invoices mainly come as attachment pdf.. a plugin reading the mail and on a given sender and subject to save the attachment in the nextcloud accountancy folder would be great and i think with a bit of fantasy such a feature would be "GOLD" and used if understood in its potential... :) i wished to give also my opinion :) cheers everybody and happy xmas

**Comment by Ark74** [comment]
I also thing this is a needed feature for improving the Nextcloud ecosystem and integration.
I suggest that @ChristophWurst could open a [bounty](https://www.bountysource.com/teams/nextcloud-mail) for this feature. So people can really show how important is this feature.

**Comment by daita** [comment]
I made this lately: https://github.com/nextcloud/files_frommail

I will see to add the feature to Mail, but there is [some dependencies](http://php.net/manual/en/book.mailparse.php) to retrieve mail attachments.

**Comment by daita** [comment]
Talking with @ChristophWurst, we need to agree on which way to do this:

- The clean and simple way: the server save the attachments when checking for new mails on request from the webclient. _The mailapp needs to be open to check for new mail_
- The more complex way: the server have it's own crontab running and check for new mails+attachments by itself. _Attachments will be saved on the cloud without the mailapp running_

My vision of the feature makes me prefer the first one. 
Also, we will use Horde, not Mailparse.

**Comment by ChristophWurst** [comment]
My vision would be solution two as it sounds like the most seamless and automated way. The first one involves too much user interaction and adds unnecessary complexity to the web client. I don't see why one only wants so sync attachments when the web client is used. They should be synced at any time.

Another aspect we shouldn't ignore: how do we handle use quota?

Yet another one: how do we handle changes on the file system? Is it read-only? Can users delete attachments? If so, will they be restored?

**Comment by daita** [comment]
Please note that the first way is totally transparent (and therefore does not add complexity to the web client). The attachments are saved from the server-side. The web client is just used to initiate the process of checking for new mails.

For the quota, we can check that n% of the quota is still available.
If user delete attachments from his files, there are just deleted. User can still download attachments from the mail itself.

**Comment by ChristophWurst** [comment]
> The web client is just used to initiate the process of checking for new mails.

I see. That introduces concurrency issues as soon as you have more than one browser window open as they don't share any state and thus the *there's new email* event might be fired multiple times for a single message.

A background job wouldn't have those issues, given that you'd make sure only one of the jobs is running at a time.

**Comment by daita** [comment]
We will encounter the same issue with the crontab way, you will still needs to find a way to check which mail+attachments have been already saved or not, as mail on the mail server will stays flagged as 'new'. This should be done by filing a table.

**Comment by ChristophWurst** [comment]
> We will encounter the same issue with the crontab way, you will still needs to find a way to check which mail+attachments have been already saved or not, as mail on the mail server will stays flagged as 'new'. This should be done by filing a table.

Nope. Simply use *horde sync*. It's a mechanism based on UIDs where you can incrementally get a list of new messages and a new token. Just store that token and use it for the next query. It won't give you duplicates :wink:

**Comment by daita** [comment]
Won't crash anything when the webclient will request for new mail ?

**Comment by ChristophWurst** [comment]
No, why would it? The web client and the background job are completely separate. The server-side is designed to be stateless and thus able to serve many clients of the same account simultaneously. Only the client-side has a state.

**Comment by ChristophWurst** [comment]
Fixed by https://github.com/nextcloud/files_frommail. Thanks @daita
