### ISSUE TITLE
File picker styling issues

### ISSUE THREAD

**Issue by onny** [nextcloud/mail#252]
### Steps to reproduce
1. Open mail with attachement
2. Save attachement to "Files"
3. Navigate to empty folder

### Expected behaviour
No styling issues, proper displaying of "close" icon and info message "No files in here"

### Actual behaviour
Info message in file picker dialog is missplaced, you have to scroll down to read it. Text overlaps the icon for closing the window.

### Mail app

**Mail app version:** 0.6.2 stable

### Note
I striped some sections of the bug report since they might not be related to the issue.

**Comment by onny** [comment]
Here are some screenshots:
![2016-12-17-233132_swaygrab](https://cloud.githubusercontent.com/assets/757752/21290194/656b58e6-c4b1-11e6-84bb-0fa9f6a0d2b0.png)
![2016-12-17-233140_swaygrab](https://cloud.githubusercontent.com/assets/757752/21290195/656ebebe-c4b1-11e6-8b31-d407ff330051.png)

**Comment by onny** [comment]
The icon on the attachement keeps spinning when you close the file picker without choosing an action:
![2016-12-17-233657_swaygrab](https://cloud.githubusercontent.com/assets/757752/21290207/e0905e7c-c4b1-11e6-9fe4-391543283f9a.png)

**Comment by ChristophWurst** [comment]
Ouch, that definitely shouldn't have happened. May I ask you to file an issue in the server repo instead? The file picker is not part of this app, we just make use of it here. Therefore I probably affects other apps too.

Regarding the loading spinner, that has to be fixed in this app. Interestingly, the code *should* remove the spinner on error too https://github.com/nextcloud/mail/blob/3df3fd194634049c65983e3440d6ff1454db2626/js/views/messageattachment.js#L80-L85.

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/mail/issues/369 and fixed by #380
