### ISSUE TITLE
STARTTLS directive from autoconfig (config-v1.1.xml) is not being adopted.

### ISSUE THREAD

**Issue by benks-io** [nextcloud/mail#2599]
### Expected behavior
If a new Mail account is added that provides autoconfiguration via url https://autoconfig.maildomain.com/mail/config-v1.1.xml the directive 
`
<outgoingServer type="smtp">...<socketType>STARTTLS</socketType>...
`
should activate STARTTL in the account settings.

### Actual behavior
After successfully adding an account via autoconfig by providing only username and password, the STARTTLS Button in the account's config is not activated, so sending of mails fails.

### Mail app

**Mail app version:** 1.1.2
**Mailserver or service:** IMAP/SMTP

### Server configuration

**Operating system**: Debian Buster

**Web server:** Apache

**DB** mysql Version: 10.3.18 

**PHP version:**  7.3.11 

**Nextcloud Version:** 17.0.3

#### Client configuration
**Browser:** Any

**Operating system:** Debian Jessie

**Comment by juergenhecht** [comment]
I've had the same experience.
In an autoconfiguration file the SocketType is marked as STARTTLS.

Nextcloud stores this entry in the database (outbound_ssl_mode) as "starttls".  However, this entry must be "tls" instead of "starttls" for Nextcloud Mails to establish an outbound starttls connection.

After manually renaming the database entry from "starttls" to "tls", the starttls mail delivery worked. In the mail account management the outgoing connection is then listed accordingly as starttls connection.

**Comment by ChristophWurst** [comment]
The code is at https://github.com/nextcloud/mail/tree/master/lib/Service/AutoConfig if anyone want to dig deeper

**Comment by apocalyptikz** [comment]
[mail\lib\Service\AutoConfig\IspDbConfigurationDetector.php](https://github.com/nextcloud/mail/blob/master/lib/Service/AutoConfig/IspDbConfigurationDetector.php)
line 220
`$account->setOutboundSslMode(strtolower($smtp['socketType']));`

Seems to setOutboundSslMode as "starttls" from autoconfig XML.

**Comment by DjSlash** [comment]
Okay, so. It's about terminology. The standard that is known by most people is 'starttls'. It's used widely, also in this app and also the autoconfig definition of Mozilla. However, at Horde, they use 'tls' ([seen here](https://github.com/horde/Smtp/blob/master/lib/Horde/Smtp.php#L860)). They mean the exact same thing. But because of this, things go faulty.

In my opinion (but I just as well be wrong), there are two options:
1. store 'tls' as setting, even when 'starttls' is issued
2. or make that translation when sending mail

**Comment by benkees** [comment]
@ChristophWurst
thanks for your hint.
I made a Pull request  #3371 that should fix the issue.
