### ISSUE TITLE
Password security issues discussion

### ISSUE THREAD

**Issue by andreas-p** [nextcloud/mail#266]
As all those zillion of password hashes from major sites published in the wild demonstrate, any site might get hacked some time.The architecture of the server application should reduce the possible impact of an intrusion, e.g. by storing strongly hashed passwords or even use an auth provider located on a different machine.
While the nextcloud passwords are hashed and thus require significant effort to reveal, the mail passwords are stored encrypted, using the "secret" from config.php. So an attacker who gained access to the server (or a malicious admin) not only can copy the encrypted passwords, but has the secret to decrypt them as well. This is even worse than weak hashes.
I'd like to use a password handling that doesn't rely on encryption. I have several NC installations that I'd like to mail-enable, giving access to the enterprise mails, using the same password for NC as for mails (actually LDAP). Technically, I'd like to reuse the NC password, instead of storing an encrypted copy in mail_accounts. Other ideas (e.g. using the user's password as secret) welcome.

**Comment by joergmschulz** [comment]
This is, IMHO, a significant leap forward security-wise.
When the mail account resides on the same security realm (i.e. the same LDAP server provides accounts to the mail server and the nextcloud server), advanced possibilities might exist; in future even PGP keys could be integrated into the security concept.
But, how could we make all this work technically?

**Comment by ChristophWurst** [comment]
Hey @andreas-p,

that totally makes sense. In fact, we're already working on a solution for a so called *default account* for setups, where the login credentials can be used for the IMAP account too, see https://github.com/nextcloud/mail/pull/28.
However, in a multi-account setup it's quite tricky to save the password securely on the server. Do you have an idea how we could solve this problem?

**Comment by andreas-p** [comment]
@ChristophWurst, good to hear about #28, I'll follow that. 
Currently, all passwords are stored using the default site secret. If This would use the user's password (or something derived from that) everything would be fine. Of course, when the password is changed, every stored password needs re-encryption. I think this would need a system-wide password storage, (i.e. not burying the password in some mail_accounts columns)

**Comment by joergmschulz** [comment]
We had such a discussion  [once](https://help.nextcloud.com/t/built-in-password-manager/204) then the [passwords](https://apps.nextcloud.com/apps/keeweb) app evolved.
Furthermore, we discussed approaches to somehow securely handle PGP private keys (no solution found and the rainloop way is considered insecure). And, people start discussing client-side encryption possibilities for owncloud (sic) in order to avoid the system wide password recovery scheme. @andreas-p : you already said the issue is a system-wide credential storage system. This is the time to involve @LukasReschke , again.
What we want to archive, is:

- safe storage, easy modification of imap credentials
- seamless login between NC and imap backends that survives password changes
- seamless first-time login to new imap accounts when imap eMail address==personal eMail address
- easy entry and safe storage for additional imap accounts
- some safe way to handle pgp private keys and en/decrypt mail (that's for version 2.x, I know)

**Comment by andreas-p** [comment]
@joergmschulz you probably meant https://github.com/fcturner/passwords and not keeweb?

I wonder if the apps/encryption lib can be re-used for this. The key handling probably should go into core, so file encryption can be enabled/disabled independently from other apps using save "stuff" storing (be it file contents or a remote server's password in the database)

**Comment by ChristophWurst** [comment]
FYI #28 has been merged.

I'm closing this ticket now due to the lack of activity. If someone wants to tackle this issue, e.g. come up with a solution for the problem or even an implementation, feel free to open a new issue for discussion. Thanks :)
