### ISSUE TITLE
Ability to load images in signatures 

### ISSUE THREAD

**Issue by JohnMaree** [nextcloud/mail#2733]
### Feature Request

The ability for signatures for each account to have images is a common feature in most email clients.

#### Summary

The ability for signatures for each account to have images is a common feature in most email clients. 
As an example:
![compact-logo-1](https://user-images.githubusercontent.com/12199888/76165774-6d7fc200-6162-11ea-998b-d780a1284790.png)

**Comment by ChristophWurst** [comment]
As briefly discussed in the dev channel, we need a permanent storage for these images. And then transform them into attachments when the messages is sent.

As a step in between we could start with external images only. This isn't ideal. But for some cases like corporate logos, this might actually just do the job.

**Comment by ChristophWurst** [comment]
Another thing that we *could* do is use ckeditor's base64 "storage". Of course this bloats messages, but for small images (like, again, logos) this could be fine. Maybe worth a consideration? :thinking:

**Comment by JohnMaree** [comment]
> Another thing that we _could_ do is use ckeditor's base64 "storage". Of course this bloats messages, but for small images (like, again, logos) this could be fine. Maybe worth a consideration? 🤔

Good idea! What makes this more appealing is the fact that typically people stray away form large signatures as loading them becomes a pain if they are too large. So one could always specify a size limit?

**Comment by ChristophWurst** [comment]
> So one could always specify a size limit?

Absolutely!

**Comment by hanserasmus** [comment]
Would it make sense to have an interim solution where the image is hosted on a third-party site like imgur.com, and have the URL pasted in the signature so that it shows up and "looks like" the image is added to the signature itself? Something similar to what google is allowing in it's gmail settings? Just until you have figured out the way forward into making it a clean integration to core code?

**Comment by ChristophWurst** [comment]
We could allow external images already, I think.

It's basically what I meant to explain with

> As a step in between we could start with external images only. This isn't ideal. But for some cases like corporate logos, this might actually just do the job.

The app wouldn't need to care where the images are stored. We'd just need to find a way to not make the browser block these images with our strict CSP.

**Comment by hanserasmus** [comment]
If you could allow them already, it would go a long way for users! I understood what you meant, just wanted clarification. Because we could create an image with all the details normally found in the signature, like the example @JohnMaree posted in the OP, and just link that in there. 

I tried adding images a while back (like 3 weeks or so) and it was not working, but might be that one needs a specific syntax for the mail client/editor to understand this imported image?

**Comment by CATER-COM** [comment]
@ChristophWurst  sorry but you closed the issue, but there is no solution provided. You said it's already possible to insert third-party image but you didn't explain the way to do it. There is no visible way in the UI.

The exchange below sound quite strange. Why we should use third-party site to embed pictures in an app designed to work in context of storing and sharing content software ???

Why we can join picture as attachment but not inside the body ?  Nextcloud Sharing Path App already deliver a way for Nextcloud to act as CDN. This process may apply to a specific folder dedicated to mail content.

**Comment by ChristophWurst** [comment]
> @ChristophWurst sorry but you closed the issue, but there is no solution provided. You said it's already possible to insert third-party image but you didn't explain the way to do it. There is no visible way in the UI.

I never claimed that. Read my comment again. It just states that your feature request is a duplicate and we have an existing ticket for discussion.

> The exchange below sound quite strange. Why we should use third-party site to embed pictures in an app designed to work in context of storing and sharing content software ???

Please carefully read the previous discussion. We want to have this, but it's not easy. So we would start small and add more advanced options gradually. But please change my mind and submit a pull request with the implementation.

**Comment by CATER-COM** [comment]
> We could allow external images already, I think.

@ChristophWurst sorry but I made tow mistake 
1 - I understood the sentence below as it's something already possible. I may was too much enthousiast ;)
2 - I thought you closed this issue not only the one i opened as duplicate :-(
Hope you will find a way. have a nice day :)

**Comment by jvalters** [comment]
Hello, but actually for Nextcloud you can use the cloud as temp storage, or the user can upload the Image into his cloud and use the public link. <--- This is Just as an idea.

**Comment by ChristophWurst** [comment]
> As a step in between we could start with external images only. This isn't ideal. But for some cases like corporate logos, this might actually just do the job.

I'm looking into this right now. Adding the CKEditor plugin is easy. BUT you won't see the image when you compose the email as Nextcloud's strict CSP will block the image URL on the Nextcloud page.

I think we'll start with the base64 insert option and the external hosting will follow later.

**Comment by ChristophWurst** [comment]
> Another thing that we _could_ do is use ckeditor's base64 "storage". Of course this bloats messages, but for small images (like, again, logos) this could be fine. Maybe worth a consideration?

So I did that

> I think we'll start with the base64 insert option and the external hosting will follow later.

But turns out this is creating more problems than it solves. It's fairly simple to add base64 images to CKEditor, but our own client can't view those messages. Turns out we're not doing it wrong, but security practice typically forbids data sources for images in email.

Some references
* Overview of email clients that can handle it https://stackoverflow.com/questions/13049453/how-to-successfully-embed-images-in-html-for-display-in-webmail-clients
* Source of the image from above https://www.campaignmonitor.com/blog/how-to/2008/08/embedding-images-in-email/
* More proof that most (web) apps block these sources https://blog.mailtrap.io/embedding-images-in-html-email-have-the-rules-changed/#Inline_embedding_or_base64_images_in_emails

So I'm concluding that this really isn't worth the effort. Let's rather have proper support for inline images that are sent as attachment. We can hopefully re-use some of our existing logic for this. Then a custom ckeditor uploader can wire the editor with our attachments.

Images as attachments doesn't solve the problem with signatures. For signatures we'll still need that special storage. This will be the most complex aspect of the whole feature.

**Comment by mmallejac** [comment]
Probably a dumb comment, but while exploring the Nextcloud filesystem, I see that the `data` folder contains sub-folders, some of them are dedicated to apps, for instance `ownbackup`, `rainloop-storage`, why not `mail` for signature images ?
The Deck app can also upload a file to a card that resides under `data-[instanceId]/deck/file-car-[id]/`

**Comment by stevearbour** [comment]
There are also very good support for all desktop mail client, and if I have people wanting to send email from their phone, using the web interface of nextcloud, it would be ideal if the person could insert the signature that he/she desire and not be coerced with some limitation because of how the mail client display message. The displaying of message and the sending of message should be totally separate in terms of managing the images... Also, normally some mail clients will detect if the images are linked with the same address that the mail server itself, the image will show otherwise simply offer a option to hide all image and only load them on demand. (antispam, image tracking, etc). IMO, you are trying to manage something that should be the job of the end client to choose and decide and that forcing people to only use Text or CKEditor is really a bad decision that prevent SMB from adopting nextcloud, I for one have at least 2 that won't switch just because of this.

All others client I know allow real signature, think about squirrel mail, roundcube, etc.

Just my 2 cents

**Comment by MohammedNoureldin** [comment]
Hi, any news regarding this?

It is gonna be great if we can set a template for the signature for every use, e.g.:

```
Best regards,
Title Firstname Lastname

Company Name

Logo Image
```

**Comment by MohammedNoureldin** [comment]
@ChristophWurst do you have any idea how the other products are doing it? For example in the company I am working for, they have an image in the signature, but I have no idea how (they use Exchange I believe). If you can give me a clue, I may support in this, I am not sure if I will have time to implement it, but at least I can give a bit more detailed information about it.

**Comment by ChristophWurst** [comment]
I think you have to proxy the image through the server, so that there is no external domain for the image. And then when the message is sent you have to rewrite the HTML to change the href from pointing to the proxy to the target URL.

**Comment by dumblob** [comment]
> @marcotrevisan, but I still don't understand how the "correct" way should be? In other words how the others are doing it? For example when I send email from my Gmail (even from my desktop client), the images are shown correctly.
> 
> What do they do to get it working out of the box? Do you have any idea about it?

That's actually really easy (to say) - namely they bundle every single referenced thing (especially pictures) with the email as separate `multipart/mixed` content (this was shown and discussed somewhere in this thread and/or the linked resources from/to this thread). Second, MUAs are highly constrained when it comes to CSS (and of course html itself, but that's easy to overcome with generic tags and styles). Basically the rule is to inline all styles (as global styles won't work) and test it on non-recent iPhone (that's probably the most constrained of all MUAs) and in the GMail web email interface (which is IMHO the second most constrained one).

But it's **not** easy to implement & test in terms of manhours needed if you think of it...

**Comment by marcotrevisan** [comment]
Hi all. Is there any progress on this issue? 
It would be great to have a way to replicate my "html signature" in Thunderbird, bad or problematic as it can be...
Thanks

**Comment by ChristophWurst** [comment]
There is no progress as you can see. The technical barriers are still there.

**Comment by stevearbour** [comment]
Lol... years later, you can clearly see why we haven't implemented or even attempted at implement next cloud/mail seriously and that for any web base email client, we went with roundcube. And it is important to note, I am myself a developer, but when we felt what was the general attitude here, following this whole post, and when facing a simple request, such as "Please let us NOT use your deficient rich text editor, and add a simple checkbox to allow us to do that on a user basis" turned into a "super complex and super biased" and turned into a "debate" discussion and into a "if you are not happy, pay us $ or do it yourself" instead of "we'll do it when we have a chance", 

Aka: Every single little things that could be found and used as a excuse, was used to divert the attention to the real problem and the real solutions. **ALL emails clients**, including most web based one, allow for HTML signature, and it is up to the user (not the developer) to decide between the catch 22 of embedded base 64 encoded image, or image hosted on the email server itself, etc. Someone clearly need to read a bit about strip_tags and filter_input PHP method, and learn about them...

Since next cloud is a multi platform and so big and way way much more complex that just "this", not only we felt that going into next cloud we would be shooting ourselves in the foot to start with, but it clearly justified all the trouble to deal with microsoft/thunderbird+caldav/roundcube scenario. It is a great solution for mom and pop who are a little into computer, but the minute your an actual business (no matter what is the size), this is ain't serious. So sorry for the other part of next cloud, it seemed a nice project, but the Mail section of the NC project is toxic in my opinion.

Have a nice day.

**Comment by foxhoundv** [comment]
Hello, so I think this is a really good idea to have and as I scanned through the previous comments I thought of a couple ways that maybe this could be implemented. I am not a programmer so just giving some ideas...

1. Reference a shared image on the Nextcloud instance that doesn't need special access. I'm guessing that `<img src>` would be the way to accomplish this and I did read that it isn't easy, just throwing out an idea.
2. Setting --> Mail page that allows uploading of an image source or file?

If I missed any of these in the discussion I'm sorry, I tried to find if there were any similar postings.

**Comment by jvalters** [comment]
Hello, is there any movement on this?

Thanks

**Comment by renatolinux** [comment]
NextCloud devs should pay attention to this request. I’ve already accessed all the topics, including this one, also without solution. I believe that such a feature should be implemented on the platform, as it is a basic feature that many people need, especially when it comes to the use of internal compliance by companies.

**Comment by kesselb** [comment]
Welcome on GitHub @renatolinux :wave: 

Please take some time to familiarize yourself with GitHub. 
Your favorite search engine may help you find matching articles. 

![image](https://github.com/nextcloud/mail/assets/3902676/872e4427-9c7c-4d30-ad4e-def2e4706e33)

An issue is open or closed. Closed + Fixed by means, in most cases, that a feature was implemented. Fixed by is the reference for the pull request that implemented the feature. It's possible to add images in signatures since Mail 2.0.

> NextCloud devs should pay attention to this request.

"should pay attention" sounds very demanding. Please use it carefully, especially on GitHub.

**Comment by sturlan** [comment]
I see this is an old and complicated topic, some issues/request were fixed/implemented but i also i see that html signature does not work.
@ChristophWurst mentioned CSP issues, and also base64 problems, also a possible proxy solution, but i didn't catch why that went as a failure.
Clearly interested in a solution, i was thinking could it be possible to rewrite message after sending and decode images to base64 (since nextcloud does not like base64).
Sorry if i got something wrong or missed a topic, i am not a programmer just throwing out an idea.

**Comment by kesselb** [comment]
@sturlan please read https://github.com/nextcloud/mail/issues/2733#issuecomment-1553520741

For help with the mail app: https://help.nextcloud.com/c/support/7 (category support, tag: mail-app)

If you are sure it's a bug, then please log a new issue here.
