### ISSUE TITLE
Deleting message doesn't reset the message view

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/mail#289]
When I'm deleting a message using the delete icon from the message list, the loaded message satys in the right panel.

![capture d ecran_2017-01-17_08-41-29](https://cloud.githubusercontent.com/assets/14975046/22011742/e2042aee-dc90-11e6-95da-2494e023763e.png)

**Comment by ChristophWurst** [comment]
I think the issue here is that we try to load the next/previous message in the list. Since there is none we do nothing.

**Comment by skjnldsv** [comment]
Is this still happening? 
I don't think so! :)

**Comment by ChristophWurst** [comment]
> Is this still happening?
> I don't think so! :)

Really? I'm a bit hesitant of closing this ticket because I'm not aware of any (intentional) fix for this :)

**Comment by jancborchardt** [comment]
The thing is that currently when deleting an email, there’s 1 second (or less) of still showing the email in the content view. I guess this is because we wait for the short deletion animation in the list to complete. It seems it’s:

1. Deletion animation in the list
2. Move to next message and clear message view
3. Show loading feedback spinner
4. Show next message

Instead we should:
1. Deletion animation in message list, and at the same time clear message view
2. Show loading feedback spinner (only if there is a new message of course)
3. Show next message

**Comment by ChristophWurst** [comment]
Original issue fixed by https://github.com/nextcloud/mail/pull/798
