### ISSUE TITLE
No messages are being displayed and there's an error icon next to each account after upgrading to 1.3.2.

### ISSUE THREAD

**Issue by RobertZenz** [nextcloud/mail#2939]
### Expected behavior

It should work.

### Actual behavior

It does not. No messages are being loaded, there is an error icon next to the accounts and clicking on the accounts does only show the preferences of said account.

The NextCloud server log does not contain any related error messages, and neither does the JavaScript console.

However, the JavaScript console shows that background jobs are running, like `mail: Inboxes sync'ed in background`, but there is not network traffic.

### Mail app

**Mail app version:** 1.3.2

### Server configuration

**Operating system**: CentOS 7

**Web server:** nginx

**Database:** PostgreSQL

**PHP version:** 7.3

**Nextcloud Version:** 18.0.3

#### Client configuration
**Browser:** Firefox 75

**Comment by ngreve** [comment]
Same here.
I thought I have to reenter my login credentials for my mail account. This did not work either. I host my own mail server,  so I checked if actually a login request is generated by Nextcloud when I try to save my login credentials. Turns out it's not. (Sending and receiving mails with Thunderbird works perfectly fine and I can see the corresponding login requests in the server logs.)

I don't know if this issue is related to the reported one, but the email service configured in the settings in Administration -> Basic settings -> Email server do not work either if I use SMTP as the send mode; send test mail fails.

**Comment by graue70** [comment]
I had the same issue after updating Mail from 1.1.2 to 1.3.2, except that the Nextcloud log showed messages like this one:
`[mail] Fatal: OCA\Mail\Exception\ServiceException: IMAP errorCould not open secure TLS connection to the IMAP server.`
I fixed it by checking my account settings in Thunderbird and copying them into my account settings in Nextcloud mail. For me, the `IMAP-Host`, `SMTP-Host`, `SMTP Security` and `SMTP port` were all incorrect.

It seems that the automatic IMAP settings logic by Nextcloud isn't quite as smart as the one by Thunderbird.

Looking at the changelog, it seems to me that the issue was introduced by the [breaking change in 1.1.4](https://apps.nextcloud.com/apps/mail/releases?platform=17#17) and probably has nothing to do with 1.3.2: 

> Security: verify TLS host by default. This can be a breaking change for self-hosted servers. If you want to return to the old insecure behavior, set app.mail.verify-tls-peer to true in config.php.

**Comment by RobertZenz** [comment]
> Looking at the changelog, it seems to me that the issue was introduced by the  > breaking change in 1.1.4 and probably has nothing to do with 1.3.2:
 > 
 > > Security: verify TLS host by default. This can be a breaking change for self-hosted servers. If you want to return to the old insecure behavior, set app.mail.verify-tls-peer to true in config.php.

That's it! I had to set it to false...which raises a few questions, for example why hosts with "Let's Encrypt" certificates are not seen as valid or trustworthy. I mean, I have two accounts, one pointing at 127.0.0.1, I can see why TLS verification on that might choke, but why does it so for my webserver host? That ones definitely correctly qualified.

Also...the UX on this one sucks.

**Comment by ngreve** [comment]
I found the cause of my problem. I did not need to set "app.mail.verify-tls-peer", the problem was on my side.
My own server was not able to resolve "(imap | mail | smpt).serverdomain.de". I could resolve this issue by adding the subdomains with their IP address to the /etc/hosts file. I probably was just lucky that this error did not show up earlier to me ...

**Comment by ChristophWurst** [comment]
> Also...the UX on this one sucks.

What a nice way to express criticism. Mind checking https://nextcloud.com/contribute/code-of-conduct/ before you post any more comments in our community? :v:

**Comment by ChristophWurst** [comment]
> That's it! Thank you. I had to set it to `false`...which raises a few questions, for example why hosts with "Let's Encrypt" certificates are not seen as valid or trustworthy. I mean, I have two accounts, one pointing at 127.0.0.1, I can see why TLS verification might choke on that one, but why does it so for my webserver host? That ones definitely correctly qualified.

Do you use the LE cert just for the web host but also the TLS of the mail server? Can you connect to the mail server with openssl on the CLI?
