### ISSUE TITLE
Prevent unread / drafts count from ever going into negative values

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#335]
There’s some error cases here and there (e.g. deleting mail and the list reloading inbetween) whereby the »unread« count can reach negative values:
![capture du 2017-03-13 11-36-19](https://cloud.githubusercontent.com/assets/925062/23850848/758f06dc-07e1-11e7-9027-cbac0e1ece6e.png)

We should prevent this by having a check like `if(unread < 0) { unread = 0; }` or something like that. ;)

@nextcloud/mail

**Comment by lcalaresu** [comment]
I don't think adding an `if` would be very wise because I have another problem with the drafts which I think is related.
When I start writing an email, it saves a draft but does not update the number of drafts in the folder list. As a consequence, I might have more drafts in my folder than written in the counter (which could lead to negative numbers when I delete more messages than that).
If I refresh the whole mail app, the draft number becomes correct however.

Maybe this problem is more for #9 ?

**Comment by ChristophWurst** [comment]
Fixed by https://github.com/nextcloud/mail/pull/326
