### ISSUE TITLE
ActiveSync support 

### ISSUE THREAD

**Issue by est42** [nextcloud/mail#336]
I'd like to see support for ActiveSync protocol in mail app.

**Comment by ChristophWurst** [comment]
Hey,

it's very unlikely that we'll work on this feature, but feel free to dive into it and open pull requests :)

**Comment by ChristophWurst** [comment]
I'm closing this ticket now since I'm not planning to span our features beyond anything that can be done with simple IMAP/SMTP.

ActiveSync could be implemented as a separate app. Check out https://docs.nextcloud.com/server/12/developer_manual/app/index.html#id1 if you're interested in working on that :)
