### ISSUE TITLE
Rubix-ML becoming global?

### ISSUE THREAD

**Issue by Rello** [nextcloud/mail#3385]
Hello @ChristophWurst 
You migrated from php-ml to rubix. 
If I am not wrong, it is shipped as part of Mail. 

What is the future strategy?
Will this be part of NC Server in the future (or is it and I am wrong)?

I am testing a usage for my apps Audioplayer and Analytics and want to avoid double shipping

Thank you for your thoughts,
Marcel

**Comment by ChristophWurst** [comment]
> Will this be part of NC Server in the future (or is it and I am wrong)?

No, there are no such plans. In fact I'm a strong oponent of this software design because it leads to unclear dependency paths between apps and what Nextcloud provides, makes upgrades and removals of libraries real pain and generally makes our development inflexible. See also my related blog post on this matter: https://blog.wuc.me/2020/05/13/rock-me-amadeus-php-dependency-hell.html.

There is an ongoing issue with rubix and mozart that has to be resolved before we can properly scope the lib like we could with php-ml. See https://github.com/coenjacobs/mozart/issues/48 and https://github.com/ChristophWurst/rubix-ml-mozart for this specific incompatibility.



> want to avoid double shipping

Double shipping is actually the preferred way of deploying software. The memory/storage benefit is minimal and the flexibility of having standalone, independent apps outweighs this downside.


PS: Sorry for the late answer, I've been on vacation for a few weeks. In general let's please have these discussions at https://help.nextcloud.com/c/dev/11 :)

**Comment by Rello** [comment]
thank you for the feedback
