### ISSUE TITLE
Search in Attachments / nextant

### ISSUE THREAD

**Issue by maldag** [nextcloud/mail#341]
It would be a great feature to bundle the search capabilities from the mail app and the nextant app to search through attachments and open it via the search function

**Comment by ChristophWurst** [comment]
This sounds interesting, though due to the fact that we're not storing any mails locally, we also do not have them available for indexing. Moreover loading all emails and their attachments is can be time/performance/bandwidth consuming and a strategy for batch processing / pagination would be required. Therefore this is largely out of scope for now, sorry.
