### ISSUE TITLE
Disable mail classifier or add option to run less often

### ISSUE THREAD

**Issue by DragonQ** [nextcloud/mail#3596]
### Feature Request

As far as I can tell, the mail classifier cannot be disabled. Every 60-70 minutes, all of my server's disks wake up just so the Nextcloud Mail app can perform this classification. I'm not even sure what mail classification does or if I want it, but I definitely know that I don't want my disks waking up 24 times a day to do this.

#### Summary

Allow the classifier to be disabled or allow the user to configure how often it runs (e.g. once per day).

Thanks!

**Comment by ChristophWurst** [comment]
I'm fine with leaving this open as a feature request. But I'm sure there is a lot of other stuff going on in Nextcloud that might cause IO activity. You might want to store this volatile data on an SSD or so. But it's really a "server" then it shouldn't have a problem with occasional disk IO.

**Comment by ChristophWurst** [comment]
Tagging *help wanted* because this isn't going on our roadmap as a niche request. But if you're interested in learning more about contributions please let me know :v:

**Comment by svalentin1984** [comment]
Hello @ChristophWurst,

I am having the same issue. I use a Nextcloud instance on a machine with 16 GB RAM, 8 Intel Xeon cores. The Nextcloud instance has aprox. 100 users. Some of the users have a mailbox of 25+ GB of email on our separate mail server. The instance serves  our faculty staff (the domain is Computer Engineering).

The email app makes the instance unusable at least once per day when the "AI" steps in. I agree that the "server" as you say should not have any problem with this... but unfortunately it does. In some cases the cron operations effectively kill the whole server keeping the CPU usage and RAM usage at maximum. I checked which part does this and it came up to be your "AI" in the email app. I could see the interrogations in the database that are made in order to do the mail classification. This "AI" has a significant impact when dealing with very large inboxes. I don't think that giving more resources to the hosting machine would solve this.

I am sorry, but I deactivated the app until there is solution to deactivate or bypass this AI. Before this feature was added everything worked great. We generally like the email app especially because it has the best integration with Nextcloud. But right now it is unusable. We moved back to the classical webmail implemented with Roundcube.

Is there absolutely no way to deactivate this AI classification ?

**Comment by ChristophWurst** [comment]
There isn't actually any "AI" in this app.

You can not disable the ML classification right now.

**Comment by svalentin1984** [comment]
I know. That's why I put the "AI" in quotes (it was the marketing naming from what I found)
The bottom line is that the classification applied of very large inboxes really crashes the server by making many large database queries. Currently I use mysql (mariadb) but in the near future I will probably migrate to PostgreSQL. I will then give the mail app another try when using PostgreSQL. Currently all the resources of the server are fully occupied by mysql and php when executing the cron.

**Comment by hbogner** [comment]
We are using Mail 1.10.0 which has following change
-Automatic message importance classification is now optional and can be turned off

I guess it is user based?
Is there a way to disable message classification globally for all users?

**Comment by ChristophWurst** [comment]
It's a user option, yes.

**Comment by hbogner** [comment]
OK, but is there any other way to disable it globally for all users?

**Comment by ChristophWurst** [comment]
Not yet but there is a ticket for this: https://github.com/nextcloud/mail/issues/5288

**Comment by ChristophWurst** [comment]
so this was actually done with https://github.com/nextcloud/mail/issues/5260. closing.
