### ISSUE TITLE
Subdirectories not working

### ISSUE THREAD

**Issue by rawbertp** [nextcloud/mail#385]
### Steps to reproduce
1. Open mail app
2. Click on an (IMAP) folder that contains subdirectories
3. The folder will not expand/shot its subdirectories

### Expected behaviour
When clicking on the "triangle" icon the folder should be expanded to shot its subdirectories.

### Actual behaviour
Nothing happens. Only the contents of the parent folder are shown (mails but not the subdirectories).

### Mail app

**Mail app version:**  0.6.4

**Mailserver or service:** Posteo

**Transport security - IMAP:** SSL/TLS

**Transport security - SMTP:** SSL/TLS

**Number of accounts:** 1

**Mail app version build date:** N/A

#### Client configuration
**Browser:** Tested in recent versions of FireFox and Chrome. No errors shown in developer console.

**Operating system:** Linux

**Comment by pixelipo** [comment]
I can confirm this issue. I have 2 Nextcloud instances on 2 different (both nxing+maridb) servers. Both have Mail 0.6.4 installed, the only difference is that the one that has this issue is on Nextcloud 12. On the other one, running 11, subdirectories work just fine.

Account is the same one, so it shouldn't be mail server issue.

I checked HTML, and it seems that the `.open` class is not added to `.collapsible` when the latter is clicked on. Instead, `.active` class is added, which does nothing in particular:
![image](https://user-images.githubusercontent.com/4129927/26929815-5a5c6c42-4c5b-11e7-8256-34036bdb26a0.png)

**Comment by lcalaresu** [comment]
I have the same problem since I am using NC 12.

It is a bit weird, the event `click .collapse` does not work anymore. 
When I click on the collapse button, the event `click .folder` is raised instead.

The Marionnette events on that view have not been changed for a really long time though... 
Maybe it is some kind of CSS collisions with the apps.scss from the NC server ; that file seems new with NC12, and introduced some `#app-navigation [...] collapse` stuffs.

**Comment by ChristophWurst** [comment]
> It is a bit weird, the event click .collapse does not work anymore.
> When I click on the collapse button, the event click .folder is raised instead.

![bildschirmfoto von 2017-06-13 13-52-09](https://user-images.githubusercontent.com/1374172/27081207-9856d6b2-503f-11e7-8a27-c17031fd9d7b.png)
looks like there's no event registered for clicking the `.collapse` element, hence the parent element gets it.

**Comment by oniehaus** [comment]
Seems to be a CSS problem. The parent folder a-Tag overlays the Button 
`<button class="collapse"></button>`

Possible workaround could be adding a z-index (append in apps/mail/css/mail.css)
```
#app-navigation button.collapse {
	z-index: 1;
}
```
At least that works for me

**Comment by lcalaresu** [comment]
> Adding a z-index [...] solves the problem for me.

Oh yeah! Works for me too (will check if there is no side effects however).
I never really got this z-index stuff (css is not "my thing" though). But now I totally get it after being pissed off for half an hour by this stupid button being under the a-link!!

**Comment by ChristophWurst** [comment]
@oniehaus thanks a lot for your patch. This indeed solves the problem. Apparently the anchor element caused a wrong navigation event whenever the user clicked the triangle. I've pushed your fix together with some other tiny fixes/cleanups as https://github.com/nextcloud/mail/pull/396 :)

**Comment by flonowa** [comment]
Hi,

I use the Version 0.7.3 and Nextcloud 12.0.3 (Nginx and MariaDB) and I have exactly the same problem

**Comment by ChristophWurst** [comment]
Please file a new ticket. Thanks!
