### ISSUE TITLE
Mark as spam auto move message to spamfolder

### ISSUE THREAD

**Issue by luvis** [nextcloud/mail#4101]
# Feature Request

Basically I would love to have the option to automatically move an email to the spamfolder when marked as spam. Once I've marked a message as spam I don't see the point in keeping it in my inbox. Maybe other people like to keep them, in which case might be able to add this as an option in settings? Its just annoying to have to mark as spam and then move -> to folder.. It takes to long, then I end up just deleting the email and spamassassin doesn't learn anything from it..

## Summary

When marking a message as spam, move message to spam folder

## Work packages

- [x] Implementation
- [x] https://github.com/nextcloud/documentation/issues/10958

**Comment by ChristophWurst** [comment]
Yeah, though we have to be careful as some mail servers do this automatically when you set the flag and others don't.

**Comment by StCyr** [comment]
What do you mean? The message would be moved on the IMAP server and the move would only be visible at next sync?

**Comment by luvis** [comment]
> Yeah, though we have to be careful as some mail servers do this automatically when you set the flag and others don't.

Sorry, I missed your response. Even if this is the case, does it matter? If i move a message and the server plans on doing it automatically anyway, won't it just ignore it since it's already been moved? Or "move it again"? Either which, if it's an option in settings, it could be disabled by default. Those who's server does it automatically, won't need to enable it but those (like me) who's server doesn't automatically move the message, can enable it. That would be great 👍

**Comment by ChristophWurst** [comment]
I guess it depends on when the server does it. If it moves right after the client adds the flag, the message to move won't exist anymore. So maybe we have to move first and then put the flag.

**Comment by StCyr** [comment]
> So maybe we have to move first and then put the flag.

Seems legit. That way we do all the work and we don't rely on the server possibly moving the message

**Comment by alexeysmovzh** [comment]
Hello Guys,

Does it any advance on this issue?

This is desired feature. 
Because users already used to this behavior with other popular web-mail systems.

**Comment by ChristophWurst** [comment]
No but we had some more findings in a duplicate ticket https://github.com/nextcloud/mail/issues/5326#issuecomment-880038311

**Comment by yitzhaq** [comment]
(From dup. #5326):

> Yes, we need a setting for the preferred junk mailbox like we have for draft, sent and trash.

I don't think you necessarily need a separate setting for that. Just use Special-Use folder designated by the server as \Junk, the same way you would use \Sent for Sent, \Drafts or Drafts etc. See [RFC 6154](https://datatracker.ietf.org/doc/html/rfc6154) for details.

**Comment by ChristophWurst** [comment]
IIRC the attribute isn't supported by all IMAP servers. Hence a setting in the client application is inevitable. Moreover you can have multiple mailboxes with the same special use attribute. How do you tell which one of the two \Sent folders is the one where a sent message should be stored? I can't find a relevant section to back my statement right now, but feel free to dig into this :)

**Comment by yitzhaq** [comment]
It's not gonna be supported by all IMAP servers, but it's been around for a decade, and has seen wide support among modern servers and clients. To my knowledge even recent versions of Outlook support it, despite it being an established and widely agreed-upon standard.

There's certainly no harm in having a setting for it, and allowing the user to override based on personal preference, but IMO the default value for the setting should be based on Special-Use as reported by the server, for Spam folder as for other folders.

The RFC seems to not explicitly deny having >1 folder share the same Special-Use value, and leaves it up to the server to decide whether doing this is a good idea. I suspect this approach is more of a catch-all statement to not rule out creative use cases, rather than something one would encounter much of in the real world. Since there's also to my knowledge no accepted standard for how to handle such scenarios, and thus clients are likely to vary wildly in their handling of it, I doubt you would need to consider this any sort of major impediment. I imagine a simple decision of only considering the last folder in a LIST with each Special-Use attribute would likely be sufficient. Basically it's a scenario where I don't think the user can reasonably expect the client to behave in a particular manner.

Here's the RFC quote you were probably looking for, BTW:

In most cases, there will likely be at most one mailbox with a given attribute for a given user, but in some server or message store implementations it might be possible for multiple mailboxes to have the same special-use attribute.

**Comment by jancborchardt** [comment]
We do have this section in the settings now:
![image](https://user-images.githubusercontent.com/925062/155130787-5a2412bd-5062-4ca2-9eff-86272228937e.png)

So we could have another entry there for spam/junk?

> IIRC the attribute isn't supported by all IMAP servers

For the ones where it’s not supported, the behavior stays the same. For those where it can be autodetected (or checked via name), it’s an improved experience.

**Comment by jancborchardt** [comment]
@ChristophWurst @miaulalala now that we have the logic for identifying the "Archive" (by @arjentz via https://github.com/nextcloud/mail/pull/7355 :), could this also be used to handle the Spam/Junk folder properly?

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/mail/issues/4101#issuecomment-748955774 is still where we are. The mailbox selection was there before. That is not the problem.
