### ISSUE TITLE
"this.account is undefined" when trying to move mails

### ISSUE THREAD

**Issue by StCyr** [nextcloud/mail#4106]
### Expected behavior
When clicking on the "Move" button, the mailboxPicker should open.

### Actual behavior
Sometimes the mailboxPicker doesn't open and the following log shows up on the console:

 TypeError: this.account is undefined
    mailboxes MailboxPicker.vue:92
    VueJS 3
    r MailboxPicker.vue:1
    VueJS 36
    onOpenMoveModal Envelope.vue:268
    click Envelope.vue:1
    VueJS 4
    onClick ActionButton.js:43
    VueJS 33

### Mail app

**Mail app version:** 1.7

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)

### Server configuration

**Operating system**: (e.g. Debian 8)

**Web server:** (e.g. Apache, Nginx,...)

**Database:** (e.g. MariaDB, SQLite or PostgreSQL)

**PHP version:** (e.g. 7.0)

**Nextcloud Version:** (see admin page, e.g. 13.0.2)

#### Client configuration
**Browser:** FF latest

**Operating system:** Windows 10 and MacOS

**Comment by StCyr** [comment]
Don't know if it's related but I also get the following error after a successful move:

Could not sync envelopes: Request failed with status code 428 Error: Request failed with status code 428
    exports createError.js:16
    exports settle.js:17
    onreadystatechange xhr.js:69
    exports xhr.js:44
    exports xhr.js:13
    exports dispatchRequest.js:52
    promise callback*c.prototype.request Axios.js:61
    e Axios.js:86
    exports bind.js:9
    e MessageService.js:69
    l runtime.js:63
    _invoke runtime.js:293
    v runtime.js:118
    u mail.js:498
    a mail.js:498
    d mail.js:498
    d mail.js:498
    syncEnvelopes mail.js:498
    syncEnvelopes actions.js:454
    g vuex.esm.js:847
    dispatch vuex.esm.js:512
    dispatch vuex.esm.js:402
    e MoveModal.vue:57
    l runtime.js:63
    _invoke runtime.js:293
    v runtime.js:118
    i mail.js:618
    s mail.js:618
    promise callback*i mail.js:618
    s mail.js:618
    onMove mail.js:618
    onMove mail.js:618
    onMove mail.js:618
    VueJS 2

**Comment by ChristophWurst** [comment]
Somehow the computed prop `account` in `Envelope.vue` must be null. Like as if the account is not in the store or the `data` (envelope) doesn't have an `accountId` set.

**Comment by brueckner** [comment]
I can reliably reproduce this when trying to move mails from within the drafts folder. When continuing to navigate to a different mailbox, the issue persists. Changing to a different account or a unified mailbox seems to re-set the account. After that it's possible to move mails again.

A simple first-aid fix would be to add a little `v-if="account"` to the `ActionButton` in `Envelope.vue`, [here](https://github.com/nextcloud/mail/blob/9669b1bea81a6feb143a27aba85ff5c19d40a54d/src/components/Envelope.vue#L89-L93). That will hide the move-button if the account is not set for a certain mailbox. However, that's just duct taping the problem...

For the draft mailbox at least, the underlying reason why the `account` property is `undefined` is simple: draft envelopes don't seem have an `accountId`. That's interesting, because they do have a `mailboxId` and that `mailboxId` **is** tied to an account. So I assume we just need to add the accountId to wherever the draft envelope is constructed and that'll properly solve this issue for draft mailboxes.

I wasn't able to reproduce it without trying to move a draft-mail first though, so there may be other circumstances where the accountId is not set on an envelope.

**Comment by StCyr** [comment]
I've just noticed that, should the "Move" action not work, then, first selecting the envelope and then using the "Move" action in the "Multi-selection" toolbar works.
