### ISSUE TITLE
Message/Thread - Mobile design

### ISSUE THREAD

**Issue by GretaD** [nextcloud/mail#4210]
### Expected behavior

- [x] The sender name when the first one its too long should still be shown and not counted(+2)
- [ ] The sender's name ( on the message )
- [ ] The subject should be shown better. Maybe ellipsized after a certain number of characters.
- [ ] The space on the right should be used. Thats a lof of unnecessary white space there
  

### Actual behavior
![design_mobile](https://user-images.githubusercontent.com/12728974/101507687-1cae2b80-3977-11eb-9c7b-477251cff7b3.png)

cc @jancborchardt

**Comment by GretaD** [comment]
@StCyr hey, can you please have a look at the first issue? The first name (the sender) should always be shown, and if its too long, it should be ellipsized and then starts the counting of the recipients. [e.g a mailing list with a ver.......  (+1)]

**Comment by jancborchardt** [comment]
Absolutely agree with your points! Some additions:
- Regarding space on the right – yep the actions should just move a bit more to the right, guess that’s some padding or margin from somewhere?
- On mobile at least, we can shorten the timestamps like Signal does: Now, 1m, 22m, 2h, 13h, Wed, Mon, Dec 3, Nov 30, Apr 3, etc.
- Since for now the subline is really just the subject repeated over and over it doesn’t add anything. So let’s just cut it. This we could even do on desktop. Yes in the future we want to show the beginning of the message of that relevant person there, but we can still add it back then, and in a better way which looks more integrated. :)

What do you think?

**Comment by StCyr** [comment]
Regarding first issue: We can specify a max-width to all RecipientBubbles. That would be an easy fix. What do you think @jancborchardt ?

**Comment by StCyr** [comment]
I've pushed a fix for the 1st issue: https://github.com/nextcloud/mail/pull/4253

**Comment by GretaD** [comment]
closing as mostly of this is delivered
