### ISSUE TITLE
Spam reporting

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#4416]
### Feature Request

As an admin I want to allow my users to report spam emails easily, e.g. to adjust filter rules on the company spam filter. There should be a system-wide reporting email configurable. When the user reports a message, an email (with the spam message attached) will be sent there. The user doesn't need to know who a message is sent to. That message should also not be stored on IMAP.

If no such reporting address is configured, the menu option shall be hidden.

#### Summary

Allow users to report spam email to their admin.

**Comment by ChristophWurst** [comment]
nevermind, I misunderstood the requirements

**Comment by ChristophWurst** [comment]
After some discussion with other developers we are unsure about why this feature would be used. Mail servers already have access to users mailboxes and the message junk flags. Existing solutions can learn from that information to train the mail server spam classification, e.g. by the bayes' theorem.

Therefore it seems redundant to have an explicit action for the user to report a message. This would only send the same information through a different channel.

Moreover an explicit report function will only work with those email clients that know how to report the email. If you set up the same account also in Thunderbird and k9, then there is no way to report the messages that are classified wrong. If you train based on user assigned flags or moving to certain mailboxes, then the mail server can improve its spam detection independent of the email client used.

**Comment by ChristophWurst** [comment]
@ArnY did we miss anything?

**Comment by ArnY** [comment]
Hello @ChristophWurst, 

Oftentime antispam systems like bayesian filters are used on MXs which are usually separate servers from the storage servers serving imap. Sometimes the MXs are even managed by another company so the service managing the filters might not always have access to the mailboxes. That's the case for us. We aren't even using bayesian filters but a markovian filter (CRM114) on 5 MXs with independants CRM114 databases. So we (and companies using external MXs services implementing antispam system for them) need a way to report detection errors and the easiest way of doing is sending emails back to the antispam system as attachment to preserve headers. I've seen companies using 2 different emails addresses depending on if the user wants to report a false negative of a false positive but we are only using one because we are using a custom script that will read headers, detect the MXs that made the error and send back the mail through that MXs telling him to learn from its mistake.

On Thunderbird we are using this addon (https://addons.thunderbird.net/en-US/thunderbird/addon/report-spam/) that  does exactly this (You'll notice it was developed by Renater to report back to their MXs provider). On other clients, our users know they can just forward misdetected mails back to us manually if really needed.

Maybe nextcloud could make that "this mail isn't a spam" or "this mail is a spam" buttons configurable in the configuration:
- forward the mail(s) to a given address (depending if the mail is a false positive or negative)
- move the mail(s) to a folder (if the mail is a spam)
- do both (we'd like that!)

I hope my point a bit more clear now...

Arnaud

**Comment by ChristophWurst** [comment]
Thanks a lot @ArnY. This sheds some light on areas we have possibly not considered so far.

Thinking more about this I also realize that we indeed do not need separate actions for *Mark as spam* vs *Report as spam*. For the users this could happen transparently, as you explained. Mail can then always alter the IMAP flag (and possibly move the message) and optionally send a report to configured email addresses.

That takes out all of the complexity from the user interface and only requires changes on the back-end.

**Comment by miaulalala** [comment]
@ArnY should this report email be sent from the user email that reports the issue or should a system account be used?

**Comment by ArnY** [comment]
Hello @miaulalala,

That's actually a good question. I hadn't thought of that. It doesn't matter since we only use the mail as a "transport" and we only care about the attached mail(s). So I suppose you can send the mail with the user's identity if that is simpler. 

Arnaud

**Comment by miaulalala** [comment]
@ArnY how should the spam email be attached to the report email, as an embedded message or as a .txt file? What does your reporting server need here?

**Comment by ArnY** [comment]
@miaulalala We need to preserve all the headers of the original mail to identify the MX server that analysed the mail, the sender, the reciptient and the antispam rules that matched so the only solution is the attach the mail(s) as "message/rfc822" attachments  The script being the report address will detect each attachment, detach it and read the headers, and then correct the adjust the antispam on the right server.

**Comment by miaulalala** [comment]
Okay awesome, thanks @ArnY !

**Comment by miaulalala** [comment]
Blocked by #5331
