### ISSUE TITLE
Subfolders

### ISSUE THREAD

**Issue by prilly** [nextcloud/mail#442]
Not possible to show subfolders inside email client..

**Comment by ChristophWurst** [comment]
Hi,

please fill out the full issue template when filing but reports like this one. Otherwise we're unable to reproduce your problem. So please take a look at https://raw.githubusercontent.com/nextcloud/mail/master/.github/issue_template.md (it was shown to you when you created this ticket already). Thanks

**Comment by ChristophWurst** [comment]
Closing this due to the lack of feedback.
