### ISSUE TITLE
Cannot delete message/thread from the thread menu

### ISSUE THREAD

**Issue by GretaD** [nextcloud/mail#4657]
### Expected behavior
 message/thread is deleted from the thread menu

### Actual behavior
After i click delete on the thread menu, the message is gone in the envelope list but the opened message on the thread doesnt go away. No error message. Then if i refresh right away, This error is shown:` [ERROR] mail: could not load envelope thread {app: "mail", uid: "greta", threadId: 13448, error: Error: Request failed with status code 403`

And the thread keeps loading and nothing happens.

### Mail app

**Mail app version:** 1.9

**Comment by StCyr** [comment]
I had a look and the issue doesn't seem easy to fix for me: 

Obviously, the MenuEnvelope component can easily forward the 'delete' event up to the Thread component, but there things become more complicated because the 'thread' object which is used to show all ThreadEnvelope in the Thread is a computed property. So, we can't delete the threadEnvelope from it and must rather rely on Vue's reactivity system to update it. 

Unfortunately, this computed property uses a parametrized getter (`this.$store.getters.getEnvelopeThread(this.threadId)`) which iinm isn't reactive.

Maybe this could be a solution: https://codingexplained.com/coding/front-end/vue-js/adding-getters-setters-computed-properties

**Comment by st3iny** [comment]
Getters can be reactive when they are wrapped in computed properties. However, I just noticed that the mutation `removeEnvelope()` does not remove references to the deleted envelope from other threads (`otherEnvelope.thread[]`). This is causing the thread view to not be reactive.
