### ISSUE TITLE
Placement of signature in E-Mail when replying

### ISSUE THREAD

**Issue by Metagit** [nextcloud/mail#4659]
### Feature Request

Currently the signature is added to the bottom of replies. If replying to some message, the quoted message will be between the  reply and the signature which is quite impractical and uncommon. Also see: https://help.nextcloud.com/t/placing-off-signature/87201

#### Summary

It would be nice to change the standard position to right below the reply.
On the long run it would probably make sense to implement a possibility in the UI to change the standard positioning.

**Comment by thstyl2000** [comment]
The reason for this positioning of signature comes from the fact that many email clients cut-off everything below "--" when adding quotes, so that no signatures would show up in replies. Putting the signature block above the quoted text would then imply that you would not see the first message as a quote if the recipient replies again. 

Maybe it makes sense to be able to add a second (third, fourth,....) signature, one directly above the quoted text without "--" and the main signature block in the end of the message:

`Example message`
Dear Alice,

thank you for your reply!

`first signature`
Best,
Bob

Am 2021-03-17 12:09, schrieb Alice:
> Hello Bob!
> 
> It looks good!
> 
> Best,
> Alice

`main signature block`
\--
Mr. Spongebob Squarepants
124 Conch St., Bikini Bottom

**Comment by ChristophWurst** [comment]
PR at https://github.com/nextcloud/mail/pull/4802

**Comment by ChristophWurst** [comment]
It's done https://github.com/nextcloud/mail/pull/4971
