### ISSUE TITLE
Secure email without PGP/SMIME

### ISSUE THREAD

**Issue by eglipeter** [nextcloud/mail#4865]
#### Summary

The user should be able to "password protect" an email message. Nextcloud then replaces the email with a standard text and a link to the Nextcloud instance. This will get mailed out to the communication partner. After typing the password, the recipient can read the email and also reply securely. For the Nextcloud user, this reply will come-in as a regular email. Also, the previously sent email will be stored in full-text in the sent folder (and not the email with the link). This would allow a basic security level for communication partners that either cannot setup proper E2E encryption or are not willing to.

**Comment by ChristophWurst** [comment]
Please browser https://github.com/nextcloud/mail/issues, there as a similar rejected request before

this sounds like a neat idea but in the end we are creating an island solution and it opens the doors for tracking who read the email, when and with what devices. So that goes against some privacy principals.

You can already use Mail to send out link shares, please use that instead

Email encryption and security is hard, we won't solve it with yet another isolated solution. For example when you send out such an email the recipient can't really reply to it easily. This will break all existing email workflows.

**Comment by eglipeter** [comment]
Okay, I see the point. In my opinion, this decision should be with the users of Nextcloud. Maybe another suggestion that I have seen commonly used in the banking industry: An automated conversion of the email to a password protected PDF. By that, there is no secure reply channel but at least a one-way secure communication is possible...

**Comment by ChristophWurst** [comment]
You can already do this. Upload that PDF to your Files and then send it as link

![Bildschirmfoto von 2021-03-31 09-29-28](https://user-images.githubusercontent.com/1374172/113106944-9d818380-9203-11eb-95fd-5e6dafcdeebf.png)

**Comment by eglipeter** [comment]
Yeah, but then I have to create that PDF by myself. I was envisioning a solution where at least for my side of the communication, I can just compose a normal email without to do x steps in addition to it. This is why I thought about the initial idea of sending a web-message to the recipient. I know that this is not satisfying from a security perspective because it is an isolated solution and there are the privacy concerns that you mentioned. The PDF solution has absolutely no back-channel. However, in my opinion both solutions are much better than nothing.
