### ISSUE TITLE
Security issue with 3rd party apps?

### ISSUE THREAD

**Issue by e-markus** [nextcloud/mail#491]
Hi,
I'm not sure whether the following is an issue or if it is not possible due to nextcloud limitations.

Possibe Steps:
- Using 3rd party apps for like caldav or carddav with a nextcloud app specific password
- connecting to nextcloud with that app password
- accessing mails via the mail app. 

Using app specific password it should not be possible to use the mail app/access users emails due to security reasons. 

As far as I understood/tested it's not possible to Login to the webinterface with app passwords. Is there any other way to access mails using any API/login that allows app passwords/authtokens?

Just in case there is an issue: I could imagine the following solution: if user is logged in with a token, accessing mails could be locked. 

Markus

**Comment by ChristophWurst** [comment]
As soon as you're logged into your Nextcloud, you can access your emails through the mail app. There's no distinction between logging into Nextcloud with your password or an app password.



> As far as I understood/tested it's not possible to Login to the webinterface with app passwords. Is there any other way to access mails using any API/login that allows app passwords/authtokens?

No.



> Just in case there is an issue: I could imagine the following solution: if user is logged in with a token, accessing mails could be locked.

What would be the use case for this?

**Comment by e-markus** [comment]
I have concerns that a 3rd party app (e.g. for calendar) could use misuse its login to access other data on nextcloud.

Mainly I can image two kind of data:
1. Files --> therefore we have the option to use app specific passwords and to revoke filesystem access
2. Mails --> Is there any way someone can access Mails using an app specific password?

> What would be the use case for this?

If (2) is possible, I would like to deny these clients from accessing my mails. 
If (2) is not possible, everything is alright  :-)

**Comment by ChristophWurst** [comment]
Okay, so you're talking about permission scopes for app passwords. Now I get it, thanks :)

We'd fist have to have scopes (other than filesystem) for app passwords in the Nextcloud server, plus an API to check permissions. Then we could implement checks inside this app.

Feel free to open a ticket at the Nextcloud server repo. I'm closing this ticket here for now because IMO that kind of security hardening is out of scope at the moment. For now I suggest to not let any non-trustworthy apps access your Nextcloud instance or don't use this app if you're that concerned about this issue. I'm sorry that I cannot provide you with a better solution right now.

Thanks
