### ISSUE TITLE
Old favorites/starred messages not synced

### ISSUE THREAD

**Issue by dakontiva** [nextcloud/mail#4939]
### Expected behavior
All starred messages no matter how old should show up in search when using the search string `is:starred`

### Actual behavior
Searching with `is:starred` only returns mails marked as favorite recently

### Mail app

**Mail app version:** 1.9.5

**Mailserver or service:** Gmail

### Server configuration

**Operating system**: Probably Debian 10 (Can't confirm as my hosting provider didn't provide it)

**Web server:** Don't know

**Database:** mysql 10.5.8

**PHP version:** 7.4.13

**Nextcloud Version:** 20.0.7

#### Client configuration
**Browser:** Firefox 87

**Operating system:** Fedora 33

**Comment by ChristophWurst** [comment]
could you inspect oc_mail_messages to find out if your older messages correctly have flag_flagged set to 1?

**Comment by thstyl2000** [comment]
So....new (unimportant) mail has arrived.

-  Without viewing it, marking it in "Others" as important gives it flag_important=1 and flag_flagged/seen=0. After around 20sec the flag disappears in the PI and the database prints flag_important=0. The same thing happens if you start in "All inboxes".
- Viewing the mail in "All inboxes" and then marking it important gives flag_important/seen=1 and flag_flagged=0. Going to the PI view changes the value of flag_important to 0. 
- Viewing the mail in it own inbox and going back to PI, keeps flag_important=1, but the frontend shows no important flag.
- Marking the mail as unread does not change flag_seen to 0.
- Now another mail arrived. Without viewing it  and marking it as important in the "All Inboxes" sets flag_important=1 and flag_flagged/seen=0 and this change remains persistent after switching to PI. The frontend then also shows the mail correctly in the "Important and Unread" section.

Can it be that the learning code is messing things up?
Please tell me if you need more tests!

**Comment by ChristophWurst** [comment]
> Can it be that the learning code is messing things up?

Nope. That code only kicks on *once* when the message first appears. There are no further modifications.
