### ISSUE TITLE
Cache all data from imap server locally

### ISSUE THREAD

**Issue by thstyl2000** [nextcloud/mail#5059]
### Feature Request

Caching of all email data locally.

#### Summary

This is a layman's opinion: since the mail app is anyway running on a server, it might make sense to cache all mail data locally by a background cron job, and then retrieve from local cache, when the user interacts in any way with the frontend. I suppose this might also solve the problem of searching in message bodies etc.

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/mail/issues/4824 is as far as we should go. A full duplication will bloat the user's storage. Having the emails locally doesn't help for search because you would still have to parse the mails individually.

This is out of scope for the next few moths, so I'm closing this feature request.
