### ISSUE TITLE
Option to move link message tags with folders

### ISSUE THREAD

**Issue by thstyl2000** [nextcloud/mail#5072]
### Feature Request

Tagging a message, creates a folder with the same name (if the folder does not already exist) and the message is automatically moved to this folder.

#### Summary

This feature request is related to a zero-inbox approach to handling email workflow (the idea is to directly categorize a message according to some rules and move it to a respective folder). Having this feature would mean that one does not have to keep track what is happening in the folders, but just giving a quick look at the respectively properly configured PI.

**Comment by thstyl2000** [comment]
Thanks for the your quick response! In order to achieve zero inbox, one has to use an effective strategy, so a high number of mailboxes is not what one would want to have. The number should be sth (much) less than 10.

**Comment by ChristophWurst** [comment]
I do understand that philosophy. But if we add this option there is no guarantee that people will use the feature with care. I can already see the reports of people that are mad because their Mail app is getting slower and slower.

We want to integrate with the Nextcloud workflow engine better in the future. There could be an option to react on tagging and then move the messages. Then you build this feature yourself on your own risk and we don't have to ship it as default feature for everyone. I think that will be the best solution for both of us.

**Comment by thstyl2000** [comment]
I see your point and if the workflow integration is in the agenda, then this is definitely the best solution. Closing.
