### ISSUE TITLE
iCloud messages indexed but not displayed

### ISSUE THREAD

**Issue by Minnietheandroid** [nextcloud/mail#5181]
Hi.
Trying out the app (it looks fantastic btw) and came across this error trying to connect an iCloud mailbox.

This or a similar issue came up a few days back and was closed for various reasons. #3401
Wasn't sure if I should continue it or not, but seeing as I'm on NC Snap, with Apache thought I'd do a fresh report.
Apologies if that was the wrong decision. Nextcloud error attached and any advice would be most appreciated.

[[PHP] Error: Error: A non-numeric value encountered.txt](https://github.com/nextcloud/mail/files/6652471/PHP.Error.Error.A.non-numeric.value.encountered.txt)

### Expected behavior
Mailbox displays messages in right hand pane

### Actual behavior
Mailbox reports correct number of messages/unread items in mailbox but doesn't display the messages or content

### Mail app

**Mail app version:** 1.9.5

**Mailserver or service:** iCloud

### Server configuration

**Operating system**: Ubuntu 20.04 - Nextcloud Snap

**Web server:** Apache 2.4 
 
**Database:** MySQL 8

**PHP version:** 7.4

**Nextcloud Version:** Snap 21.01

#### Client configuration
**Browser:** Firefox 89.0, Brave 1.25.68

**Operating system:** Manjaro 21

**Comment by ChristophWurst** [comment]
> A non-numeric value encountered

This one still puzzles me. Could you try with detailed logging as documented at https://github.com/nextcloud/mail/blob/master/doc/admin.md#logging? I'd like to see the IMAP communication where an UID isn't a number.

**Comment by Minnietheandroid** [comment]
Thank you for the reply Christoph.

I was able to retrieve the nextcloud.log and the horde_imap.log but couldn't find the smtp one, 
perhaps because I haven't sent an email out yet? I don't know.

Personal info replaced with USERNAME and LOCALIP.

Thank you for looking.

[nextcloud.log](https://github.com/nextcloud/mail/files/6654635/nextcloud.log)
[horde_imap.log](https://github.com/nextcloud/mail/files/6654636/horde_imap.log)

**Comment by Minnietheandroid** [comment]
Sorry, wasn't thinking clearly.
I sent an email and got the smtp log you need.

[horde_smtp.log](https://github.com/nextcloud/mail/files/6658458/horde_smtp.log)

**Comment by Minnietheandroid** [comment]
Hi and thanks very much @miaulalala for having a look.
Is this something I could go in and fix up, somewhere inside the snap?

**Comment by miaulalala** [comment]
Hi Minnietheandroid, it looks like it's just the first issue, but I haven't been able to load my mailbox contents now. So it seems this empty string from the iCloud IMAP is causing more than just this issue. I'll debug further and let you know what I find.

**Comment by Minnietheandroid** [comment]
@miaulalala I don't know how the code works but I'm up for testing or anything else that may help.
Thanks again.

**Comment by miaulalala** [comment]
So after spending some time debugging the mysteriously vanishing message, it turns out that we're receiving the same UIDs for changed and vanished messages from the iCloud IMAP server. At least my Inbox does, which leads to the message being deleted at the first partial sync.

@Minnietheandroid how proficient are you with PHP? Would you be able to confirm this from your side?

If you add this function 

```php
$in = array_filter($in, static function($id){
    return is_int($id);
});
```

to the Horde_Imap_Client_Ids::_toSequenceString function like so: 

![image](https://user-images.githubusercontent.com/7427347/122356658-4ada7c80-cf53-11eb-9cbf-75a07816e384.png)

you should be able to get your mailbox set up.

 The first sync (`ImapToDbSyncronizer::initialSync` ) will show your messages, but the second (`ImapToDbSyncronizer::runPartialSync`) will delete them again.

If you set some break points in apps/mail/lib/IMAP/Sync/Synchronizer::sync, you should be able to see the different UID arrays (`$changedUids` and `$vanishedUids`.

In case you miss the intial sync, you can set the sync tokens to `null` in `oc_mail_mailboxes` so it will trigger a new initial sync.

I closed the frontend and triggered the sync via command line with the `occ  mail:account:sync your-account-id-here` command which makes it easier to debug just the one request.

**Comment by Minnietheandroid** [comment]
@miaulalala I've added the function to -
 /var/snap/nextcloud/28088/nextcloud/extra-apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Ids.php 
![grab](https://user-images.githubusercontent.com/3885113/122397671-86f5f780-cfbc-11eb-9771-e7fe57f6212a.png)

The 'Error: A non-numeric value encountered etc'' has stopped in the admin loggging page, 
but still no messages at that point.

Moving on to setting sync tokens to null and I'm quite lost. I can't figure out how to trigger a new sync.
Sorry I can't provide more information yet but I'll crack on again tomorrow.

**Comment by miaulalala** [comment]
@Minnietheandroid thanks so much for taking the time! If you want some help, join us in the [public groupware dev channel](https://cloud.nextcloud.com/call/5qb8fujz)!

**Comment by Minnietheandroid** [comment]
Thank you @miaulalala, that looks really interesting!

I rechecked with 3 fresh Hanssen Nextcloud VM instances today, 
hoping that would get around any re-syncing issues without me taking a dive into php I know nothing about.
It also best represents a brand new install.

VM1. Installed and patched the /Horde/Imap/Client/Ids.php before adding the icloud account.
That got rid of the 'non-numeric value encountered' error, but still no messages.

VM2. Left unpatched. Just added the icloud account.
That gives 'the non-numeric value encountered' error, and no messages.

VM3 Unpatched using a different (non icloud) imap account, no error and shows the messages.

Not sure where that leaves us, at least some of the way there though.
Hats off to your mad skills:)

**Comment by miaulalala** [comment]
@Minnietheandroid thanks again for checking, I think this kind of confirms my theory on vanished and changed IDs! Not sure what the next steps are yet, but I'll keep you updated in any case.

**Comment by jkrack** [comment]
Just wondering if you all landed this one? At this point I’d pay for the right dev to help all of us out. Love this app, and want to fully use NextCloud.

**Comment by NQuebec** [comment]
Hello,

I, too, have this exact same issue, using Nextcloud 22.2.3 and configuring the email app with iCloud.

When you are concerned with privacy it makes sense to host Nextcloud and use iCloud (Apple) as an email provider, specially since iCloud recently added support for custom domains.

I strongly appreciate the high quality work being done by Nextcloud developpers and hope this issue will get to a resolution some time soon.  iCloud is far from being a small email provider and it fits perfectly with Nextcloud values.

Thank you again and keep going the excellent work.

**Comment by jkrack** [comment]
@NQuebec is your instance of Nextcloud sitting behind SWAG or a Reverse Proxy by chance? I'm continuing to self diagnose to see if its something within my setup. I noticed the basic data elements are coming through (email count, inbox quota), which is most likely transported over 443, but maybe the actual email comes through 993. Which is currently something I'm trying to configure correctly within SWAG (which is a reverse proxy for security). 

When I look at the logs, I can see Mail iterating through the list of emails, but without the actual guts of the email. I'm going to focus on configuring SWAG with 993 to see if that changes anything. 

My stack:
Unraid
LinuxServer.IO SWAG docker container:latest
LinuxServer.IO  Nextcloud docker:latest
Unifi - Home networking gear (ports forwarded to Unraid 443 and 993)

No luck yet, but hopeful that the time off this holiday will let me dig in a bit further.

**Comment by NQuebec** [comment]
@jkrack yes my instance is behind a reverse proxy (nginx).  I have the exact same behavior as you describe: email count and folders name get refreshed but emails don't show.  Your hypothesis is interesting, I'll try too to forward port 993 within my reverse proxy.

My Nextcloud instance isn't installed through docker but native with PHP-FPM and proxied via nginx.

One last thing: Few weeks ago I had downloaded and installed the [bitnami image of Horde Groupware email](https://bitnami.com/stack/horde) to test it and got the exact same issue we are discussing here: folders and emails count were updated but emails weren't downloaded.  I'll have to check if this setup involved a reverse proxy.

**Comment by NQuebec** [comment]
While experimenting with other webmail clients (Roundcube, Afterlogic and Rainloop) I found that enabling emails threads on a specific email account with iCloud prevents the webmail client to get the messages, but not the folders and attribures.

I didn't find such an option ("use email threads") in the config of Nextcloud mail app but if you find it and disable it then I am 99% confident this issue will be resolved.

**Comment by jkrack** [comment]
This is really great insight @NQuebec, I tipped you with the small amount of Brave credit that I had (more just testing out the feature, :) ) . @ChristophWurst any thoughts on how we could help dig deeper into this one? Super appreciative of all of the work on the Mail app. My only thought is dig into which app is using email threads and see if I could change the behavior. One question I do have for you though, do you know of anyone that has iCloud email setup successfully?

**Comment by miaulalala** [comment]
@jkrack We've changed some stuff in the sync logic since then so I'm not sure how up to date this issue still is. If you have any insight, I would be super grateful if you are willing to share :)

I recently tried setting up an iCloud account again and I'm running into a endless loop for the sync now.

**Comment by jkrack** [comment]
Hey @miaulalala, I'm using Mail app version 1.11.5, on Nextcloud Hub II (23.0.0) and still experiencing the issue. I've removed and added the icloud account again, but same behavior. 

![image](https://user-images.githubusercontent.com/369185/148653105-808e8658-3ff9-4692-bf95-dd889193c034.png)

**Comment by miaulalala** [comment]
Thanks @jkrack for letting me know.

I think I am on the way to at least knowing the reason for this behavour. The MIN:MAX search for the highest and lowest known UID return 0 for my iCloud account.

If anyone here is capable of doing a bit of PHP debugging, I would be super grateful if you could set a breakpoint at https://github.com/nextcloud/mail/blob/2287909eaa2387dfb603c202438c0b9d04aa5913/lib/IMAP/MessageMapper.php#L102-L118 and tell me the values of  ```$metaResults, $min, $max``` and ``` $total```

**Comment by jkrack** [comment]
I'm not saavy enough to debug, just dangerous enough to set a debug level and share logs. :)

Appreciate you continuing to look into this one!

**Comment by ktemkin** [comment]
I've taken a peek at this, today; and it looks like Apple's servers legitimately omit the MIN and MAX fields from search responses, even when they're explicitly requested.

I've been having some luck just treating the servers like they don't support the `ESEARCH`, since they don't seem to support it _properly_. Perhaps we can get something like the Horde bug #9842 workaround, but for platforms that advertise themselves as supporting apple's push capability?

**Comment by ktemkin** [comment]
It seems like Apple's implementation has some issues with their `ESEARCH` and `BINARY` support. I've submitted a PR to Horde that fixes the iCloud related issues For Me:

https://github.com/horde/Imap_Client/pull/17

Anyone interested in giving this a try?

**Comment by ChristophWurst** [comment]
Thanks a lot for the thorough debugging @ktemkin. We could check if there is an alternative approach to finding the min/max UIDs if icloud has issues with the existing search operation.

**Comment by Final-Hawk** [comment]
Hi, I'm looking to use iCloud email with nextcloud on truenas. Has there been any updates to this issue?

**Comment by ChristophWurst** [comment]
No, not yet

**Comment by ChristophWurst** [comment]
Resetting the status because this got stale again.

**Comment by romcheg** [comment]
@ChristophWurst I do realize you and your team have other priorities and I would like to help fixing this issue. I am an experienced developer and an SRE so I can debug things and fix them. However, I lack useful knowledge about PHP and IMAP so I need some initial guidance.

With Google forcibly switching their old Google Apps accounts to paid plans many people move their mailboxes to iCloud because it allows to attach a custom domain with no extra charge, if one's using a paid storage plan.

With that, I am ready to invest my time and effort into fixing this issue or finding a useful workaround for it but I kindly ask for your or one of your teammates' assistance to at least start looking in a right place.

**Comment by richardoswald** [comment]
I am also experiencing similar behavior with iCloud messages . I am running Nextcloud 27.1.1 with mail app 3.4.1. I would love to provide logs or to help debug this issue.

**Comment by Luncheon3462** [comment]
bump
