### ISSUE TITLE
Mailbox names with different number of trailing whitespace considered identical

### ISSUE THREAD

**Issue by miaulalala** [nextcloud/mail#5200]
### Expected behavior

Mailboxes can be named with and differentiated by whitespace characters at the end.

### Actual behavior

Unique Constrain Violation when trying to sync and write mailboxes. 

The reason being that text values are whitespace padded (at least in MySQL):
https://stackoverflow.com/questions/59504215/how-to-add-white-space-at-the-end-of-word-while-inserting-data-into-mysql

**Comment by ChristophWurst** [comment]
I've updated to reflect that this isn't just about the duplication problem at insert.

If you create a mailbox "I haz whitespace " you'll very likely be unable to actually use it in Mail because Mail will try to open "I haz whitespace" on IMAP.

**Comment by st3iny** [comment]
Mailbox names should be encoded before being saved in the database to prevent his problem. However, doing so incurs a costly migration that needs to rewrite all rows.

**Possible solution:** Add a new row `name_is_encoded` (default: 0) and just encode new mailbox names from now on. It is important to **only** encode names with trailing spaces as the uniqueness constraint will break otherwise.

**Comment by ChristophWurst** [comment]
An alternative to encoding could be a new column with a mailbox hash name and move the unique index over to the new column. Then we don't have to come up with an encoding and the integrity (no duplicate mailboxes per account) is still guaranteed.
