### ISSUE TITLE
Enable Caching for HTMLPurifyer

### ISSUE THREAD

**Issue by miaulalala** [nextcloud/mail#5250]
We're currently not caching the HTMLPurifyer definition.

We could and should cache this to improve how fast message bodies load, but there is a (now closed but unresolved) [ticket](https://github.com/owncloud/core/issues/10767) attached.

**Comment by ChristophWurst** [comment]
What exactly do you want to cache?

Let's do some profiling before we dig into this. Currently a big source of body loading delay is https://github.com/nextcloud/mail/issues/4823. https://github.com/nextcloud/mail/issues/4824 will make fetching of the body from IMAP obsolete in some cases.

**Comment by miaulalala** [comment]
I'm going off the comment in [Mail\Service\Html::sanitizeHtmlMailBody`

https://github.com/nextcloud/mail/blob/13284caccc82e89dcf38811734839ff46156f97f/lib/Service/Html.php#L135-L136

and the documentation for [HTMLPurifyer](http://htmlpurifier.org/live/configdoc/plain.html#Cache.DefinitionImpl) which suggests that there is a penalty for not caching.

**Comment by ChristophWurst** [comment]
Got it. Let's throw blackfire against it to see how bad the code actually behaves without caching

**Comment by st3iny** [comment]
First observation: The builtin cache implementation requires an absolute path. This is a problem because we can only generate file handles using IAppData. Solution: Implement custom cache class based of HTMLPurifier_DefinitionCache.

**Comment by ChristophWurst** [comment]
This needs some careful evaluation. Ideally we would push into a local memory cache behind the ICache abstraction. IAppData has potential latency for any non-local primary storage and creates a bottleneck because storage is centralized.

Our debugging showed that small to medium sized emails didn't spend too much time in the purification process and most emails are only read a few times. So unless we pair this with cache warming, the caching alone will always have low impact on the typical Mail app usage.

Let's put this aside for another time.
