### ISSUE TITLE
Whitespace missing between accounts

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#5271]
There used to be whitespace above the account names for visual separation in the navigation, now there is none and it’s all just one list:
Mail nav before with whitespace | Mail nav now, no vertical whitespace
-|-
![mail nav before](https://user-images.githubusercontent.com/925062/124280189-ac503d00-db48-11eb-9774-e8343a895efa.png) | ![mail navigation](https://user-images.githubusercontent.com/925062/124279984-6a26fb80-db48-11eb-9add-bd5578530e55.png)

**Comment by ChristophWurst** [comment]
Possibly a regression from upgrading to nc/vue v4. @GretaD could you check if one of the selectors doesn't select anymore? The css for the spacing should still be in our code base.

**Comment by GretaD** [comment]
> Possibly a regression from upgrading to nc/vue v4. @GretaD could you check if one of the selectors doesn't select anymore? The css for the spacing should still be in our code base.
Removing this line: https://github.com/nextcloud/nextcloud-vue/blob/551e5562a8c23b88dd177655562afacbc9861e42/src/components/AppNavigationSpacer/AppNavigationSpacer.vue#L35
resolve the problem. We dont have any other css rule on mail. So i think, adding order 0 on our code, should be a solution, because i dont think we should touch the nc/vue
