### ISSUE TITLE
Add system-wide configuration parameter to disable classifier

### ISSUE THREAD

**Issue by hostingnuggets** [nextcloud/mail#5288]
### Feature Request

Add system-wide configuration parameter to disable classifier for every one.

#### Summary

This could be implemented for example as a parameter in config.php or in the the settings of the web interface when logged in as administrator.

**Comment by ChristophWurst** [comment]
I suggest there could be a system config flag instead of the hard-coded 'true' at https://github.com/nextcloud/mail/blob/0f1d9e528cffcf7cc17730503a8fde01c600e059/lib/Controller/PageController.php#L161 and https://github.com/nextcloud/mail/blob/0f1d9e528cffcf7cc17730503a8fde01c600e059/lib/Listener/NewMessageClassificationListener.php#L82, then user still have the option to toggle this preference but admins can set their preferred default.

**Comment by antoineguichard** [comment]
Has this been implemented, by any chance?

**Comment by hostingnuggets** [comment]
@antoineguichard LOL you wish :rofl:

**Comment by ChristophWurst** [comment]
Full instructions are above. If this is important to you feel free to contribute or hire someone who can do it for you.

**Comment by ltsavar** [comment]
Can be closed. See #6390
