### ISSUE TITLE
Internal server error when trying to read some mails

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/mail#5325]
https://cloud.nextcloud.com/apps/mail/api/messages/1996286/thread
https://cloud.nextcloud.com/apps/mail/api/messages/1996271/thread

Return 500s for me.

```
{"status":"error","message":"Server error","data":[],"code":0}
```

**Comment by ChristophWurst** [comment]
Unfortunately I'll need some logs.

**Comment by diegotorreslopez81** [comment]
I had same issue, here more detail:
Expected behavior

Since the last two updates, 1.10 and 1.10.1, I cannot receive email from the Mail App in Nextcloud, but I can from any other mail client.
Actual behavior

When trying to access Mail, it doesn't open the mailbox from the Mail app.
Mail app

1.10 and 1.10.1
Mail app version: (see apps admin page, e.g. 0.5.3)

Mailserver or service: (e.g. Outlook, Yahoo, Gmail, Exchange,...)
Mail-in-a-box
Server configuration

Operating system: (e.g. Debian 8)
Ubuntu 18

Web server: (e.g. Apache, Nginx,...)
nginx

Database: (e.g. MariaDB, SQLite or PostgreSQL)
mysql

PHP version: (e.g. 7.0)
7.3

Nextcloud Version: (see admin page, e.g. 13.0.2)
20.0.1
Client configuration

Browser: (e.g. Firefox 48)
Firefox 89.0.2

Operating system: (e.g. Arch Linux)
Windows 11
<img width="1909" alt="Screenshot 2021-07-13 205033" src="https://user-images.githubusercontent.com/22802165/125509608-bda04b32-acf2-4ec0-a7f3-e5907015d7dc.png">
<img width="1048" alt="Screenshot 2021-07-13 205010" src="https://user-images.githubusercontent.com/22802165/125509611-301afd05-0ccd-4c44-b3eb-74d54910aa0e.png">

**Comment by ChristophWurst** [comment]
@diegotorreslopez81 I don't think your bug is related.



> Unfortunately I'll need some logs.

``Argument 2 passed to OCA\\Mail\\Service\\MailManager::getThread() must be of the type string, null given, called in /var/www/html/apps/mail/lib/Controller/MessagesController.php on line 310``. So that message doesn't have a thread root ID, while it should have one … suspicious.

Another weird log from the same request URL
``Argument 7 passed to OCA\\Mail\\Controller\\MessagesController::__construct() must be of the type string, null given`` 

And an unrelated but not unimportant cron error
``Cron mail sync failed: Sync failed for 65:INBOX: An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '69142-5861' for key 'mail_msg_mb_uid_idx'``.

**Comment by ChristophWurst** [comment]
I would suggest that we check our code for all paths where we set the thread root ID to make sure that the value is always set. Messages should point to themselves as thread root by default. If no message ID is set then we use the autogenerated one. After the threading algo we must not ever assign `null` as thread root.

**Comment by diegotorreslopez81** [comment]
Thanks for answering @ChristophWurst, where should I check this? just to inform, if I use another mail client it works.
