### ISSUE TITLE
Custom Development?

### ISSUE THREAD

**Issue by klevans123** [nextcloud/mail#5353]
### Feature Request

1) End-to-end encryption
2) OpenPGP support
3) New Mobile Skins
4) Scheduling and Delaying Email

#### Summary

Hi,

I wanted to know if you guys would be willing to develop the above for features for me. I really want to add End-to-End encryption for emails sent to other users that use my mail system which is running on top of cPanel email. OpenPGP will be used for sending and receiving encrypted emails to users outside my mail system. Also want to make a skin or theme that is more mobile friendly. The first 3 items are the most important to me. 

The 4th item is something I would love to add also, but is not that important.

If this is something you guys could do, please let me know cost to add these features.

Thanks,

LaMon Evans
901-591-0034 cell
Skype:  klevans123

**Comment by GretaD** [comment]
#648 we closed a similar request because this feature is still way off our roadmap. 

Are you already our customer, if yes, please let us know so we can direct you to our sales team. 
If you are an individual, then we cannot prioritize this because we normally do not take paying features request, from individuals.

**Comment by ChristophWurst** [comment]
There is also a freelance section in our forum: https://help.nextcloud.com/c/nextcloud-freelancing/48
