### ISSUE TITLE
Eternally loading mail

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/mail#5357]
### Expected behavior
I'd like to read my mail :D

### Actual behavior
Loading screen stays forever.

### Mail app

cloud.nc.c and nextcloud mail server.

#### Client configuration
Google Chrome 92.0.4515.107 (Official Build) (64-bit)

**Operating system:**
openSUSE Tumbleweed (everything latest)

Here's the browser log:

[mail not behaving cloud.nextcloud.com-1627041946244.log](https://github.com/nextcloud/mail/files/6868601/mail.not.behaving.cloud.nextcloud.com-1627041946244.log)

**Comment by ThomasSteinbach** [comment]
Same problem here. Nextcloud Mail just showing "Lade Nachrichten" (loading messages). After a couple of minutes the server log shows

```
Allowed memory size of 17179869184 bytes exhausted (tried to allocate 1073741832 bytes) at /var/www/html/custom_apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Ids.php#178
```

That means that Nextcloud Mail eats up all my PHP `memory_limit=16G` - which is quite a lot. I have about 8.000 mails in my IMAP account. Rainloop would instantly showing up my inbox. However I would rather like to use the official Nextcloud mail app.

* Nextcloud Mail 1.10.4
* Nextcloud Server 21.0.4-fpm

**Comment by ChristophWurst** [comment]
8k messages should not be a problem. We've tested with accounts up to 300k messages.

Could you check nextcloud.log for a trace? It's strange that building the IDs object is blowing up the memory.

**Comment by jasond2020** [comment]
I have the same Problem: Mails are loading forever (and most of them never show) - but only on android. The logs do not show any errors. Mails are loading (a bit slow, but showing up eventually, when connecting from a windows or linux pc). 

This is on NC 22.2.0, debian 11.1, php 7.4, apache2, mariadb 10.5; mailapp-version 1.10.5 (but this problem exists for some time now... maybe since version 1.3 or 1.4)

only thing showing up in the logs is with loglevel 0 are entries like these:
Debug	mail	Account 3 has 0 messages with a new thread IDs	

Debug	mail	Account 3 has 3251 threads	

Debug	mail	Threading 3399 messages took 0s	

Debug	mail	Threading 3399 messages - group by subject took 0s	

Debug	mail	Threading 3399 messages - prune containers took 0s	

Debug	mail	Threading 3399 messages - free ID table took 0s	

Debug	mail	Threading 3399 messages - build root container took 0s	

Debug	mail	Threading 3399 messages - build ID table took 0s	

Debug	mail	Account 3 has 3399 messages for threading	

Debug	mail	Unlocking mailbox 32 from new messages sync	

Debug	mail	Unlocking mailbox 32 from changed messages sync	

Debug	mail	Unlocking mailbox 32 from vanished messages sync	

Debug	mail	partial sync 3:INBOX took 2s	

Debug	mail	partial sync 3:INBOX - persist new messages took 0s	

Debug	mail	partial sync 3:INBOX - get vanished messages via Horde took 0s	

Debug	mail	partial sync 3:INBOX - persist changed messages took 0s

**Comment by hermesalvesbr** [comment]
I saw a post with the same problem here

https://help.nextcloud.com/t/mail-app-email-loading-slow/109993

**Comment by jasond2020** [comment]
a bit late my answer, but the problem is still the same (nc 23.0.2 ...): and no, no running out of memory, no hints in the debug log that give me any hint what is happening. are there some php-related configurations that i am missing?

**Comment by ruedigerkupper** [comment]
I have a similar issue, but I'm not sure if it's the same underlying problem:
Mails do not render in the mail app (all I see is an endlessly circling icon). When I click the three-dots-menu -> furtther actions -> show source, I see the full source of the mail body. So fetching the mail from the server works okay.
What fails is rendering it inside the mail app. Any idea what causes rendering to fail?

**Comment by joshtrichards** [comment]
Summary of key errors from OP's (@jospoortvliet) report (i.e. what *this* Issue is about):

```
/apps/mail/api/messages?mailboxId=2728&limit=20:1 Failed to load resource: the server responded with a status of 409 (Conflict)
/apps/mail/api/messages?mailboxId=2728&filter=is:pi-starred&limit=20:1 Failed to load resource: the server responded with a status of 409 (Conflict)
/apps/mail/api/messages?mailboxId=2728&filter=is:pi-important&limit=20:1 Failed to load resource: the server responded with a status of 409 (Conflict)
/apps/mail/api/messages?mailboxId=2728&filter=is:pi-other&limit=20:1 Failed to load resource: the server responded with a status of 409 (Conflict)
​ [INFO] mail: Mailbox unified (is:pi-other) is locked Object
```

```
`ConsoleLogger.js:33 [INFO] mail: Mailbox unified (is:pi-important) is locked {app: "mail", uid: "jos", error: MailboxLockedError
    at p (https://cloud.nextcloud.com/apps/mail/js/mail.js?v=f2012be1-69:68:562)…}
xhr.js:177 GET https://cloud.nextcloud.com/apps/mail/api/messages?mailboxId=2728&limit=20 409 (Conflict)`
```

@ThomasSteinbach: Your initial outward symptom may be similar, but unclear whether it's a related issue without any provided logs. Unless your logs look similar to the above, your situation is unrelated. If still having the problem, please open an independent Issue please.

@jasond2020 Your situation seems unrelated to this Issue. Please open a dedicated Issue if you're still having this problem.

@ruedigerkupper Thanks for your report, but appears unrelated to this Issue. Can you please open a dedicated Issue if you're still experiencing this?
