### ISSUE TITLE
Move new message composer into a modal

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#5483]

**Comment by alexanderdd** [comment]
I know a lot of email apps are doing this. But is it really a good idea compared to status quo of the NC mail webinterface?

On small screens, will it look good? Will we loose screen space because the modal is not using the full available width/height for message composition?

**Comment by jancborchardt** [comment]
@alexanderdd yes so we did some research, here’s the explanations:

The ideal goal would be to have it like Gmail does (or FB messenger) with a collapsible message window in the bottom right. However since we can’t really smoothly keep that in place, especially when switching apps, it would give people a wrong impression of what it can do – at least at this stage.

Then regarding the current approach, it is kind of a weird inbetween: The folders and messages still show on the left, but if you click them, the composer closes – so functionally it’s basically like a modal anyway. But composer is off to the right and there’s a whole lot of other stuff going on. Also there’s the really strange sending feedback which just kind of stays there, which we could do much nicer with a modal.

This is why we prefer the modal approach: Centered, focused, the rest is subdued. You can concentrate on writing the mail.

> On small screens, will it look good?

On small screens, we can force the modal to go into "fullscreen" mode, so no space is lost. :)
