### ISSUE TITLE
Menu button overlaps

### ISSUE THREAD

**Issue by That-Guy-Jack** [nextcloud/mail#5492]
spacing needs adjusting to make the menu icon not overlap the content on the page 

![image](https://user-images.githubusercontent.com/56127525/131335025-22eb4ec2-000a-4944-b5e4-269b7388e2e2.png)

### Mail app

**Mail app version:** 	1.10.3

### Server configuration

**Operating system**: Ubuntu 20 LTS

**Web server:** Apache

**Database:**MariaDB

**PHP version:** 7.4

**Nextcloud Version:** 22.1.1

#### Client configuration
**Browser:** chrome

**Operating system:** Win10

**Comment by GretaD** [comment]
Hello @That-Guy-Jack, I guess you mean when you are on Inbox view the *Hamburger menu* or AppNavigationToggle overlaps. We have couple of discussion on how to fix that. I am closing this issue since its a doublication and continue here: https://github.com/nextcloud/server/issues/16934 if theres any update.

Thanks for the report.
