### ISSUE TITLE
send button above Message

### ISSUE THREAD

**Issue by bread-on-toast** [nextcloud/mail#5627]
Maybe there could be a second Send button aboth the message.
This would be especially useful with mail conversations where with lots fo cited text the mail gets very long.

**Comment by ChristophWurst** [comment]
@nimishavijay :eyes:

**Comment by nimishavijay** [comment]
Agreed, there should a send button that's always visible.
I would go with maybe a sticky send button at the bottom (by making the entire bottom bar sticky) instead of another send button on top, since in many cases the length of the message can be quite short and then 2 send buttons would be visible.
Then the body of the message could be scrollable, like in Gmail.

![image](https://user-images.githubusercontent.com/52440189/137726012-2319d4e5-3dfe-425b-8a54-ee0cb696660f.png)

What do you think?

**Comment by caasi-dev** [comment]
> Agreed, there should a send button that's always visible. I would go with maybe a sticky send button at the bottom (by making the entire bottom bar sticky) instead of another send button on top, since in many cases the length of the message can be quite short and then 2 send buttons would be visible. Then the body of the message could be scrollable, like in Gmail.
> 
> ![image](https://user-images.githubusercontent.com/52440189/137726012-2319d4e5-3dfe-425b-8a54-ee0cb696660f.png)
> 
> What do you think?

This would be great!

**Comment by GretaD** [comment]
> Agreed, there should a send button that's always visible. I would go with maybe a sticky send button at the bottom (by making the entire bottom bar sticky) instead of another send button on top, since in many cases the length of the message can be quite short and then 2 send buttons would be visible. Then the body of the message could be scrollable, like in Gmail.
>
So you are proposing to have the formatting bar sticky in the end and below that the the send button on the left? We dont have the other options like images or emojis, so that doesnt apply.

**Comment by nimishavijay** [comment]
> So you are proposing to have the formatting bar sticky in the end and below that the the send button on the left? We dont have the other options like images or emojis, so that doesnt apply.

Yes, the formatting bar can go above the send button, but it could remain hidden by default, only shown when formatting is enabled.
The send button can stay on the right as it is now :)

**Comment by bread-on-toast** [comment]
Is there a branch with sticky send button, because this would be a feature I'd really appreciate ;)

**Comment by snyssen** [comment]
Just came here to say that resolving this issue would really be great for me too. We often have lengthy exchanges with clients, meaning that to send a response I often have to scroll a lot since these exchanges are sometime close to hundreds of mails long. I know I could just use the <kbd>ctrl</kbd> + <kbd>enter</kbd> shortcut, but it actually never worked on my end (though I guess I should report that in another issue.

**Comment by ChristophWurst** [comment]
as per https://github.com/nextcloud/mail/pull/5513 the composer is now in a modal and I think that makes the interaction clearer.

may I ask you to check out v1.12 once we release it and have another look?

**Comment by caasi-dev** [comment]
> as per #5513 the composer is now in a modal and I think that makes the interaction clearer.
> 
> may I ask you to check out v1.12 once we release it and have another look?

Modal would work for me perfectly, can't wait for a release !

**Comment by snyssen** [comment]
> as per #5513 the composer is now in a modal and I think that makes the interaction clearer.
> 
> may I ask you to check out v1.12 once we release it and have another look?

I didn't know that was coming, it looks perfect, thank you !

**Comment by ChristophWurst** [comment]
Editor is now a modal
