### ISSUE TITLE
 Improve the way attachment look

### ISSUE THREAD

**Issue by GretaD** [nextcloud/mail#5768]
We should improve how attachments look on the composer. Right now it looks like this:
![attachment](https://user-images.githubusercontent.com/12728974/144313713-0e969b31-bba2-4201-bed9-6b5afa4fdf6d.png)
cc @nextcloud/designers 

## Tasks
- [ ] #6310 
- [x] #6660

**Comment by nimishavijay** [comment]
Something like this would work? Attachments are shown below the message in a separate section, and because the modal has less space it is expandable/collapsible.

When collapsed
![image](https://user-images.githubusercontent.com/52440189/145570435-5593dfdd-9cab-48fa-b475-ca4e7c991abd.png)

When expanded
![image](https://user-images.githubusercontent.com/52440189/145570477-9631d750-0c8d-4c97-a052-c8d23dd929a9.png)

When there are many attachments
![image](https://user-images.githubusercontent.com/52440189/145570502-3fc92adf-7316-438c-b039-de7ce089feb4.png)

Things to note:
- The section would be collapsed by default
- The icon next to each attachment would be its preview if available, otherwise its filetype icon (is this possible?)
- If there are many attachments the section would be scrollable 
- Unrelated to attachments, but we could also move the discard draft button and "Saving draft"/"Draft saved" indication to the left 

cc @jancborchardt for any extra feedback as well :)

**Comment by jancborchardt** [comment]
Looks amazing @nimishavijay! :) Only 1 feedback:

> The section would be collapsed by default

I’d say the section collapsing/grouping should only happen once there are more than 2 attachments present (or rather: more attachments than fit on one row). If it’s just one row, then the space the toggle takes would be the same as the attachments itself would take.

**Comment by GretaD** [comment]
this ticket is outdated, there were many improvements on attachment display
