### ISSUE TITLE
Use Undo Sending for "Send now" button in the outbox

### ISSUE THREAD

**Issue by miaulalala** [nextcloud/mail#6248]
When using the "Send now" button in the outbox, also trigger an undo send for the message.

**Comment by jancborchardt** [comment]
> Confirmation for the action I am about to do

I’d say confirmation is not necessary, since:
- We don’t ask for confirmation for deletion or sending in normal cases either
- For sending we offer undo send, so that would show up here as well, no?
- Deleted mails would be moved to the trash, so could be recoverable


> "Message Sent" / "Message Deleted" Modal or Toast.

Yep, as notification toast would be good. Modal is too prominent in this case, as people want to continue with their other stuff, so it can’t be blocking.

- "Message sent" with undo would be great
- "Message deleted" is also good, and I assume having undo for that is a separate issue?

**Comment by jancborchardt** [comment]
If undo for "Send now" from the outbox is difficult for whatever reason, we can also go with a modal for now.
