### ISSUE TITLE
Set default date and time for "custom send time" to one hour into the future

### ISSUE THREAD

**Issue by miaulalala** [nextcloud/mail#6269]

**Comment by JuliaKirschenheuter** [comment]
I've looked into possible implementation and seen, that it is not so easy to set a time for "custom send time" to one hour into the future, because of the calculation of "disabled datetimepicker-date" and "disabled datetimepicker-time". If we want to have a disabled date / time - we have to make sure, that it will not be recalculated each time the user pick a new date/time.

@st3iny do you have some ideas to this point?

**Comment by st3iny** [comment]
Something like 

```js
const selectedDate = new Date()
selectedDate.setHours(selectedDate.getHours() + 1)
```

in `data() {[...]` should work.
