### ISSUE TITLE
Pull-to-refresh doesn’t work when a folder is empty

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#639]
### Steps to reproduce
1. Have an empty drafts folder
2. Write a reply or a new mail, then do something else
3. Go into the drafts folder

### Expected behaviour
The draft shows up

### Actual behaviour
The folder is empty, and pull-to-refresh doesn’t work either.

You need to refresh the whole app for the drafts to show. Even when there are already drafts in the folder, you need to manually pull/scroll to refresh.

**Comment by ChristophWurst** [comment]
> Draft folder is not refreshed when navigating into it

None of the folders is refreshed when navigation into it right away. They get updated in the background though, which might take up to half a minute.

> pull-to-refresh doesn’t work when it’s empty

I think I know the problem. And it's not bound to the drafts folder, but happens in any folder. The problem is that no `scroll` event is fired by the browser. Have you tried the `r` shortcut? Would be curious if that works. I expect it to work because that's unrelated to the scrolling bug but triggers the same action.

Since this is not really a regressions (was the same for several releases IIRC), I'm removing the label. Additionally, I'll update the title according to my feedback above.

**Comment by jancborchardt** [comment]
Yes, the `r` shortcut works, even when the scroll event does not.

**Comment by ChristophWurst** [comment]
Great. Thanks for checking.

**Comment by GretaD** [comment]
Outdated, the drafts work fine now
