### ISSUE TITLE
Microsoft 365 changes Oct 1 2022 and the effect on this app

### ISSUE THREAD

**Issue by bwragg** [nextcloud/mail#6591]
### Is your feature request related to a problem? Please describe.

As announced here:

[https://techcommunity.microsoft.com/t5/exchange-team-blog/basic-authentication-and-exchange-online-september-2021-update/ba-p/2772210](url)

& 

[https://techcommunity.microsoft.com/t5/exchange-team-blog/basic-authentication-deprecation-in-exchange-online-may-2022/ba-p/3301866](url)

Microsoft are going to turn Basic Auth for IMAP & POP from October 1 2022. No exceptions.

I've been searching for a way around this but there doesn't seem to currently be one apart from stopping using the Mail app.

### Describe the solution you'd like

Is there another way in the for connecting to 365 (Exchange Online) accounts? The documents above link to this article:

[https://docs.microsoft.com/en-gb/exchange/client-developer/legacy-protocols/how-to-authenticate-an-imap-pop-smtp-application-by-using-oauth](url)

This is something that could be/is planned to be implemented? Or is the approach not suitable for Nextcloud (due to the mail app fetching via IMAP done on the server side). Is there another way it could be done?

**Comment by ChristophWurst** [comment]
I'm looking into https://github.com/nextcloud/mail/issues/6454 right now. The changes sound similar. Gmail has already shut down their basic IMAP logins, for Outlook we have a bit of time.

**Comment by andyxheli** [comment]
@ChristophWurst 
https://learn.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/deprecation-of-basic-authentication-exchange-online

Looks like MS did disable Basic authentication for Outlook, EWS, RPS, POP, IMAP, and EAS protocols in Exchange Online.

Is there any talk about supporting Exchange Active Sync with the Mail App? Since that's the standard and recommended solution for  Exchange Online account these days. Especially with 2fa being enforced on the O365 tenants + alot of Orgs disable from allowing them to create app password and tell you the truth most users wouldn't even know how if you show them too

**Comment by ChristophWurst** [comment]
This app is an IMAP client. I don't think any other protocol fits the architecture at the moment.

**Comment by ChristophWurst** [comment]
The changes are done: https://github.com/nextcloud/mail/pull/7722. Time for a technical review and testing by developers.
