### ISSUE TITLE
Sender of thread message not vertically centered

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#6621]
### Steps to reproduce

1. Open a thread (can be one message only)
2. Look at the avatar/sender

### Expected behavior

Avatar and sender are on one line

### Actual behavior

Sender floats above the avatar base line.

![Bildschirmfoto vom 2022-06-01 09-14-43](https://user-images.githubusercontent.com/1374172/171348842-89f8750b-7664-47bd-b819-250718427fa7.png)

### Mail app version

1.13

### Additional info

@GretaD you worked on the thread subject logic. Can you tell why the sender isn't centered (anymore)?

**Comment by GretaD** [comment]
I remember not centering the sender because of the tags, also, when i removed the subject here: https://github.com/nextcloud/mail/pull/5496 there's no styling to change the sender position so this was always the behavior i would say. BUT, we can definitely change it and make it look nice with the tags

**Comment by ChristophWurst** [comment]
Yes please. It looks broken right now.
