### ISSUE TITLE
App does not prevent accidental leave that causes data loss

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#6627]
### Steps to reproduce

1. Compose a new message
2. Before draft saving kicks in, close the tab

### Expected behavior

The app asks me for confirmation and only drops my data if I consent.

### Actual behavior

Data is silently dropped.

### Additional info

This can be solved by JavaScript's `onbeforeunload`.

**Comment by thstyl2000** [comment]
It's actually even more troublesome in the following case:

1. Start writing an email.
2. Draft is saved for the first time. "Draft saved" notification is shown.
3. Continue writing for some time. "Draft saved" notification is continuously shown.
4. Remember sth you need to check from another email.
5. You close the editor directly.
6. You lose your last couple of sentences because the email is saved periodically.
