### ISSUE TITLE
Loading indicator issues

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#7268]
### Steps to reproduce

1. Go to the Mail app
2. In any folder, press the refresh button
3. Also press the `r` keyboard shortcut

### Expected behavior

You get quick and nice loading feedback in both cases. Now that we have the dedicated "Refresh" button, we can just make that one spin instead of having a separate spinner below which makes the message list move. (Cause that also makes the app look a bit unstable.)

### Actual behavior

For the `r` keyboard shortcut you get a spinner, while for pressing the "Refresh" icon, you get nothing.

### Mail app version

2.0.0-beta.5

**Comment by GretaD** [comment]
The first part of this ticket is fixed here: https://github.com/nextcloud/mail/pull/7373

related to when you press _r_, state that can be fixed with the skeleton #7308 here, because unless you are looking at the refresh button on the header, i dont think you can notice that some loading/refresh is happening if you dont have it visually on the envelope list. cc @jancborchardt

**Comment by ChristophWurst** [comment]
@GretaD is this done?
