### ISSUE TITLE
Blocked images element has white background in dark mode and is not aligned

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#7325]
### Steps to reproduce

1. Switch Nextcloud to the dark theme
2. Open a HTML message with external images

### Expected behavior

Nice UI

### Background color is wrong

![Bildschirmfoto vom 2022-09-27 09-56-31](https://user-images.githubusercontent.com/1374172/192468153-2071651e-33e9-4b35-baa5-39669f7c3f24.png)

### Text doesn't align
![Bildschirmfoto vom 2022-09-27 09-57-55](https://user-images.githubusercontent.com/1374172/192468145-e5a353c5-8117-481c-97d5-50e0eeece154.png)

### Mail app version

v2

**Comment by GretaD** [comment]
i cannot reproduce this with any html msg i have on my inbox, including a paypal one. Are you really on v2? Asking because i dont see the line frame on message, looks like box-shadow we used to have
![Screenshot from 2022-09-28 10-03-40](https://user-images.githubusercontent.com/12728974/192723878-579b30e6-ad23-462e-bfeb-ba1ea6fa01b7.png)

**Comment by ChristophWurst** [comment]
Switch your browser to dark mode

**Comment by GretaD** [comment]
> Switch your browser to dark mode

yes its in dark mode, theming and browser

**Comment by JuliaKirschenheuter** [comment]
I can't reproduce it too

![image](https://user-images.githubusercontent.com/6078378/194275538-4360b892-91c3-4cf8-8597-4d7c72abf5ff.png)

**Comment by ChristophWurst** [comment]
I'm not able to reproduce anymore either. It must have been fixed in server, possibly by a css var.
