### ISSUE TITLE
Decoding mangled for some first message lines in preview

### ISSUE THREAD

**Issue by roliverio** [nextcloud/mail#7408]
### Steps to reproduce

1.  Go to Mail app
2.  List messages (either on inbox or navigating to folder)
3.  See mangled preview

### Expected behavior

Correct preview decoding

### Actual behavior

Mangled preview / unintelligible on message list 

### Mail app version

1.14.0

### Mailserver or service

Dovecot

### Operating system

Debian 11.0

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database

MariaDB

### Additional info

It is a particular issue as this happens only for some specific messages from various senders (there are senders where preview is shown correctly), also, this was not happening some Mail versions ago.

Attached is a message source summary with the first 3 _actual_ message lines (all sensitive information has been redacted sans subject)

Also, a short capture on how the message preview on the message list is seen.

![sshot_nexcloud_mail](https://user-images.githubusercontent.com/390821/195099237-c7e9ff10-16be-451a-ada6-812482e57256.png)
[message_summary.txt](https://github.com/nextcloud/mail/files/9756094/message_summary.txt)

**Comment by radek3911** [comment]
I also have similar issue, but with UTF-8 encoding
![image](https://user-images.githubusercontent.com/15276167/195853234-a0e88f0d-085a-4863-8fbb-1d8b76cfbdd6.png)

You can see that in title it parses UTF-8 characters correctly (ENÉ)
but in the preview line you can see =20 =20 (or known otherwise as UTF-8 space symbol)

I have tracked it down to content type of email.. 

If Content-Type header in .EML is:
`Content-Type: text/html; charset="utf-8"`
It parses UTF8 characters correctly

When Content-Type header in .EML is:
`Content-Type: multipart/mixed; boundary="10422 . . . d854"`

It shows =20 and other UTF-8 as unparsed. (This can be further pointed out to emails with attachment as multipart is used for emails with attachments)

![image](https://user-images.githubusercontent.com/15276167/195853929-0a3a3c27-8026-4dbf-a638-e43a23b48bda.png)


This could be a different issue who knows - since in the original issue the message does not include attachment.

**Comment by ChristophWurst** [comment]
![Bildschirmfoto vom 2022-10-19 14-35-08](https://user-images.githubusercontent.com/1374172/196692214-928d345e-452f-4ac9-b579-ccdd587b8e58.png)
![Bildschirmfoto vom 2022-10-19 14-35-00](https://user-images.githubusercontent.com/1374172/196692238-04f8b421-784e-4397-86af-3994530d95a0.png)

**Comment by ChristophWurst** [comment]
We read the data at `\OCA\Mail\IMAP\MessageMapper::getBodyStructureData`

**Comment by the-djmaze** [comment]
Here's a base64 one:
![afbeelding](https://user-images.githubusercontent.com/3752035/198333036-6ca67bf3-72df-42fe-a96c-0c77f11e2e14.png)

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/mail/pull/7486 will fix this. The bug happens with multipart messages that have HTML and text parts. Then the header for the transfer encoding is lost and no decoding happens.
