### ISSUE TITLE
Wrong timezone for Google Agenda invitation

### ISSUE THREAD

**Issue by Mer0me** [nextcloud/mail#7458]
### Steps to reproduce

1. Create a meeting in Google Agenda 
2. Send invitation to a Nextcloud user
3. The mail app displays different timezones for the meeting (UTC or CEST in my case)

### Expected behavior

Timezone of the meeting should be consistent everywhere (including agenda app)

### Actual behavior

On the Mail app :
![image](https://user-images.githubusercontent.com/6248852/196705469-bcd24e12-38ff-4350-8073-81e3947e8ff9.png)

On the Agenda app :
Meeting is placed on the good time slot on the agenda, but when clicking on the event for editing, something is wrong :
![image](https://user-images.githubusercontent.com/6248852/196705839-87ddc381-a52b-4bed-9bd0-d53051c076a1.png)

### Mail app version

2.0.3

### Mailserver or service

Sender : Google, Receiver : Postfix / Dovecot

### Operating system

Debian 11

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database

MariaDB

**Comment by ChristophWurst** [comment]
@st3iny :eyes:

**Comment by JohannesGGE** [comment]
I tested it and got the following results:
#### Mail app:
I couldn't reproduce it. It may already be fixed. We used old timezone data in the calendar-js library, so this could have caused the issue here. @Mer0me Do you still have the issue in new versions of the Mail app?

#### Agenda/Calendar app:
Because the event was created in a different timezone than the Calendar app is set to, the data is converted to display it. The event itself keeps the data unconverted, so when you try to edit the event, the displayed time is the time of the original timezone. You can see that when you select the timezone next to the time:
![image](https://github.com/nextcloud/mail/assets/74607597/e087a994-d52f-4352-b76c-051be5f51a2d)
Not sure if that is intended behavior, but I think so. @ChristophWurst

**Comment by ChristophWurst** [comment]
Good observation. The time picker shows time in the target timezone, not the local one. This can be confusing.

There was a discussion about this internally. One idea would be to make it more prominent that the time is in another TZ, e.g. by rendering local time below the datepicker.

**Comment by Mer0me** [comment]
Could not reproduce the bug now. I close this one.
