### ISSUE TITLE
To field dropdown is extremely buggy

### ISSUE THREAD

**Issue by MagsMagnoli** [nextcloud/mail#7506]
### Steps to reproduce

1. Click new message
2. Enter multiple addresses in the to field
3. Try to edit addresses in the to field

### Expected behavior

- Clicking x to remove should work
- Addresses shouldn't disappear when input is focused
- Should show existing emails when an existing one is entered

### Actual behavior

- Emails disappear 
- Pressing x does nothing
- Shows a no results found message

### Mail app version

1.14.1

### Mailserver or service

Docker mailserver

### Operating system

Ubuntu

### Web server

Apache (supported)

### Database

MySQL

### Additional info

https://user-images.githubusercontent.com/4146037/198904968-c1520ff1-7e84-4a2f-b01b-19057f220557.mov

**Comment by ChristophWurst** [comment]
:eyes: @GretaD

**Comment by LostinSpacetime** [comment]
This might be another bug, but scrolling the addresses when the field is expanded doesn't work either. It shows only the first two rows.

I wonder if this is a problem with our setups or if this is a problem everybody using Mail 1.14.1 experience, since this bug(s)  make the To field basically unusable.

**Comment by GretaD** [comment]
this looks similar to this: https://github.com/nextcloud/mail/issues/7260

i can reproduce it. Will have a look asap
