### ISSUE TITLE
Verify signed S/MIME messages

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#7666]
### Is your feature request related to a problem? Please describe.

As a user I want to see if an incoming message signed via S/MIME has a valid signature.

### Describe the solution you'd like

The app shall use the signature information attached to a message to verify if the contents have been tempered with. Moreover, the app shall check if the sender used a valid certificate. For infrastructure independence it could be wise to use Nextcloud's shipped CA bundle.

The trust model is to protect messages outside the boundaries of an organization. Therefore the server and its admins are trusted. Public and private keys may be known in plain text on the server-side.

The trust model is to protect messages outside the boundaries of an organization. Therefore the server and its admins are trusted. Public and private keys may be known in plain text on the server-side.

### Describe alternatives you've considered

N/a

### Additional context

This is part of https://github.com/nextcloud/mail/issues/7085.

**Comment by st3iny** [comment]
I just debugged a weird problem when playing with `openssl smime -verify` and the respective php function. It turns out that the key usage and extended key usage properties of the CA certificate have to be set correctly. Otherwise, openssl will fail with `Verify error: unsupported certificate purpose`.

This might be interesting to document for admins. Then again, they should already know that and are probably experienced with S/MIME.

Ref https://groups.google.com/g/mailing.openssl.users/c/5qekR--kfAA
Ref https://help.hcltechsw.com/domino/11.0.0/conf_keyusageextensionsandextendedkeyusage_r.html#:~:text=Key%20usage%20extensions%20define%20the,%2For%20non%2Drepudiation%20extensions.
