### ISSUE TITLE
The images have been blocked to protect your privacy.   Show images font is white on white background

### ISSUE THREAD

**Issue by ioscanner** [nextcloud/mail#7736]
### Steps to reproduce

1. open any email that has images hidden.
2. The link: The images have been blocked to protect your privacy.  Show images  is all white so you can't see it.

### Expected behavior

Should be able to see the link: The images have been blocked to protect your privacy. 

Show images in black font on a white background.

### Actual behavior

The font is white on white background so you can't see it.  It should be black font on white background and white on black background.

I do have the standard official dark mode enabled.

### Mail app version

2.2.0

### Mailserver or service

Zimbra

### Operating system

Ubuntu 22.04.1 LTS

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database

MySQL

**Comment by ChristophWurst** [comment]
screenshot?

**Comment by ChristophWurst** [comment]
> I do have the standard official dark mode enabled.

Nextcloud? OS? Browser? Please check and specify all three. It does make a difference sometimes.

**Comment by FlorisTheBeast** [comment]
I'm experiencing same issues as described here.
I was able to reproduce the issue in Firefox and Chromium on Linux (Manjaro Linux to be exact) and I have not tested any other browsers.
You can reproduce this issue by switching to dark theme and taking a look at the "Show Images" button.
Because of the dark theme the text becomes white but the border where this text is contained within stays white, resulting in the text becoming almost impossible to read.

What I would suggest to fix this is keeping the text of the "show images" button dark or changing the email border to be dark when using the dark theme.

I  am currently running Nextcloud AIO 9.1.0 with Mail version 3.7.2 and Nextcloud version 29.0.3

Dark Mode
![Screenshot_20240713_041256](https://github.com/user-attachments/assets/c90ea1f3-1012-44ed-bec3-66ce438e98dc)
Light Mode
![Screenshot_20240713_041435](https://github.com/user-attachments/assets/4297aa96-d39c-445f-9ea1-9d703815d005)
I hope this helps with fixing this issue
