### ISSUE TITLE
🔎📄👤 Search message body

### ISSUE THREAD

**Issue by frederikb96** [nextcloud/mail#8050]
### Is your feature request related to a problem? Please describe.

If I enter a search phrase in the search box of a folder, only the message subjects are searched.

### Describe the solution you'd like

Option 1: Automatically also search within the message body and the sender emails adresses.
Option 2: Under filter, provide a checkbox for search message body and senders.

### Describe alternatives you've considered

Solution can be combined with #8030

### Additional context

It would be very nice to have this feature, as it is standard in other mail clients.

Thank you very much :)

**Comment by Djiock** [comment]
Glad to see there is already an issue opened, it is indeed pretty standard. The app improved greatly lately though, thanks for that ! Hoping to see this implemented soon.

**Comment by KimmoJ** [comment]
Agreed, came to point this out also. Right now, search is pretty bad since you need to know the subject to have a shot at finding anything, really. This applies both to the global search (at least the email section in the global search) and the search inside the mail app itself. Arguably, if you just enter a search term it should search _all text anywhere probably even including headers_ in my opinion. Then you could optionally limit the choices in the targeted search UI. My workaround for now is firing up another webmail solution entirely (SOGO) whenever I need to search. But yeah, just entering a search term should find that in any text in any mail imo, unless you specify you want to search just a subsection like topic or sender.

**Comment by ChristophWurst** [comment]
I've studied the code a bit. The app does have capabilities to contact IMAP for body search. Right now the search bar always sends off a search for a subject match only. E.g. if you enter "test" in the search input, a request with "subject:test" is sent. This is also documented at https://github.com/nextcloud/mail/pull/6546#issuecomment-1195253032.

**Comment by TheDBP** [comment]
Just adding my interest in seeing this feature added. I love all the Nextcloud integration, the design is clean, in general I really love this webmail client but unfortunately with the search in the state it's in, my organization can't rely on it. Would much prefer to use this client than any other, but we really need a more robust search feature for that to be feasible.

**Comment by ChristophWurst** [comment]
We don't use bounties

**Comment by ChristophWurst** [comment]
Sender/recipient is searched since https://github.com/nextcloud/mail/pull/8645
