### ISSUE TITLE
[Feature Request] Need Elasticsearch support

### ISSUE THREAD

**Issue by HLFH** [nextcloud/mail#816]
Hi,

IMHO, search can be quite slow, supporting Elasticsearch may improve a lot search.

Thanks,
HLFH

**Comment by ChristophWurst** [comment]
Hi,

thanks for you report. While I know that search indeed can be quite slow, it's merely due to poor IMAP support for fast searches. On IMAP servers that have certain IMAP capabilities enabled, search can be acceptably fast. However, on others it sometimes slow, especially for large mailboxes.

I have no plan of integrating elastic search in this app. I'm pretty sure there's a lot we could improve in the app, possibly by doing more efficient IMAP queries or trying to cache more of the fetched data to reduce data transfer times.

If you're interested in helping making search queries faster, I suggest to attach a profiler to your Nextcloud instance to identify bottlenecks.

**Comment by HLFH** [comment]
@ChristophWurst 

> On IMAP servers that have certain IMAP capabilities enabled, search can be acceptably fast.

I guess you are using Dovecot. So which IMAP capabilities will you enable in Dovecot or in the IMAP solution you are using to make search quicker?

Thank you!

**Comment by ChristophWurst** [comment]
IIRC it's `SORT`.

**Comment by mateuszkwiatkowski** [comment]
This could help: https://github.com/atkinsj/fts-elasticsearch
