### ISSUE TITLE
Primary action menu overlaps with recipient on small screen

### ISSUE THREAD

**Issue by GretaD** [nextcloud/mail#8191]
### Steps to reproduce

1. Open mail on small screen
2. Look at one thread header
3.

### Expected behavior

Nice design

### Actual behavior

I cannot read the recipient

### Mail app version

3.0.0-beta

### PHP engine version

None

### Web server

None

### Database

None

### Additional info

![Screenshot from 2023-03-03 09-57-49](https://user-images.githubusercontent.com/12728974/222690523-41ce5d4b-67a2-4737-992b-bb01c0605526.png)

**Comment by GretaD** [comment]
@jancborchardt @nimishavijay @ChristophWurst this is a space issue. How should we solve it design wise?

**Comment by nimishavijay** [comment]
For sure a space issue. As the screen width decreases the items of the primary actually menu could go into the 3 dot menu, starting from the rightmost action (so as the screen size decreases, the Delete action would be the first to go inside the 3 dot menu). 

Additionally, since Reply is the most important action here we could show that outside the 3 dot menu always. What do you think?

**Comment by ChristophWurst** [comment]
More examples

![Bildschirmfoto vom 2023-03-21 09-27-49](https://user-images.githubusercontent.com/1374172/226557417-778226f3-901a-4d7b-b56b-391a8074d7e5.png)
![Bildschirmfoto vom 2023-03-21 09-28-56](https://user-images.githubusercontent.com/1374172/226557430-66457619-5459-4d66-ac3c-6f191953fb32.png)

**Comment by nimishavijay** [comment]
Since there is a lot of useful information shown in that header area, we could also make the avatar smaller to 32px on mobile since there are no actions associated with it. One use of it would be to detect fraudulent mails (for example the fake Frank doesn't have a photo), and that is easy to identify even if the avatar is smaller.
