### ISSUE TITLE
Mail address not visible

### ISSUE THREAD

**Issue by hamza221** [nextcloud/mail#8379]
### Steps to reproduce

1. Open a message in your mailbox
2. try to find the email address of the participants 

### Expected behavior

Finding the email address of the participants should be easy and intuitive

### Actual behavior

When clicking on the participant label the email address gets immediately hidden  

### PHP engine version

None

### Web server

None

### Database

None

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/mail/issues/7884#issuecomment-1502858743 is where this was brought up.

@jancborchardt @nimishavijay how can we restructure this so it's both secure (sender email clearly visible by default) and looks good?

**Comment by nimishavijay** [comment]
There are 2 places where the email address can be shown but is currently hidden. 

The first is the list of participants in the header of the entire thread. Here you can see the participants' names and when you click on it to find out more, the email address appears in a popover but is immediately hidden by another popover with email actions.

![image](https://user-images.githubusercontent.com/52440189/232770622-04ece3bd-b519-40b0-ba04-a5d059d2be33.png)

---
![image](https://user-images.githubusercontent.com/52440189/232770402-ff7e0af4-1421-4274-8ce5-0c413e1debf8.png)


The popover which covers the email is currently not using any component, and looks visually very different from anything else we have. We can change this to an action menu with the email as the first item which cannot be clicked on. (I've not included the "Contacts with this email" part because it doesn't seem to work anywhere? At least not on the company instance?)

![image](https://user-images.githubusercontent.com/52440189/232809463-fdaa5c3f-9191-4bef-8027-1c0083a32821.png)

The second place where this appears is in each message header. Here, only the name of the sender is shown. I would suggest we show the email address in another row in `--color-text-maxcontrast`, so that it looks similar to a list item. On mobile it can be hidden by default as likely it is too wide. 

![image](https://user-images.githubusercontent.com/52440189/232762005-2650b132-7c95-4c39-865c-0292fde31560.png)

What do you think? cc @jancborchardt

**Comment by ChristophWurst** [comment]
> Hence I would say it is okay to hide the email address in the thread header, while showing it properly in the message header.

Sounds good and I think that is a fair middleground between design and security :+1:

**Comment by hamza221** [comment]
After:
![image](https://user-images.githubusercontent.com/40746210/234257378-3e684682-36fe-4314-9cb0-c839a5783b5b.png)
Before: 
![image](https://user-images.githubusercontent.com/40746210/234257759-2fcec915-18b3-4763-8bc9-01534bbf7bf2.png)
would moving all actions to the action menu on mobile be a good solution for this?

**Comment by ChristophWurst** [comment]
Tracked in https://github.com/nextcloud/mail/issues/8191. You can ignore the space issue for this change. We'll address it separately :+1:
