### ISSUE TITLE
Cannot handle calendar invitation update

### ISSUE THREAD

**Issue by kuba-orlik** [nextcloud/mail#8458]
### Steps to reproduce

1. As user A, invite user B to a calendar event as an attendee. User B Receives an email with an .ics file
2. As user B, accept that invitation and add it to user B's calendar by using the "add to calendar" button. It appears now in users B's calendar.
3. As user A, change the date of the event. User B receives an email with an updated .ics file. 
4. Open the email as user B

### Expected behavior

There should be a way to update the date of the event accepted in step 2

### Actual behavior

There's no way to update the event in the calendar to the newest version

### Mail app version

2.2.6

### Mailserver or service

n/a

### Operating system

Linux

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database

MySQL

**Comment by beccon4** [comment]
As of Version 3.3.0 the "Calendar import popup" is fixed. I currently run 3.3.1 and it shows the following behaviour:

- an incoming calendar invitation (ics file originating from MS Outlook) is correctly recognised. I can clearly see the appointment's date, time and invitation text. 
- then I want to insert it into  my calendar. I would expect a button above or below - or an option in the ... menu. It is actually in the 2nd sub -  menu - additional actions - create appointment. Never mind. 
- clicking this menu entry brings up a popup window with some but not all content of the appointment and the current date instead of the appointment's.
- before I can do anything, the popup simply disappears

There  is no way to simply download the .ics file and import it manually. (as Mail recognises it as an invitation) . This kind of behaviour is around for some time now and renders the  Mail app quite unusable for business use containing appointments etc.

**Comment by GretaD** [comment]
related: https://github.com/nextcloud/mail/issues/8753
