### ISSUE TITLE
Cannot modify email address

### ISSUE THREAD

**Issue by oparoz** [nextcloud/mail#862]
### Steps to reproduce
1. Go to settings
2. Change email address

### Expected behaviour

Done

### Actual behaviour

App just hangs

I've tried to use the advanced settings.

1. Login parameters automatically change to the email address, even though that's not what's being used to connect to my account
2. After having saved and got confirmation that data was changed, nothing had changed. A refresh showed me the old configuration.

### Mail app

**Mail app version:** Latest

**Mailserver or service:** Dovecot

**Number of accounts:** 1

### Server configuration

c.nc

**Comment by ChristophWurst** [comment]
Hi!

Thank you for your report. It looks like your report is missing some important sections of your [issue template](https://raw.githubusercontent.com/nextcloud/mail/master/.github/issue_template.md). Please complete it so that we get a better understanding of your setup and the problem to be able to fix the issue.

Thank you.

**Comment by ChristophWurst** [comment]
> Login parameters automatically change to the email address, even though that's not what's being used to connect to my account

This happens because we re-use the setup view and there we copy the email address as default imap/smtp username for convenience sake.

> After having saved and got confirmation that data was changed, nothing had changed. A refresh showed me the old configuration.

Couldn't reproduce right away but I'm digging deeper.
