### ISSUE TITLE
Ethical AI rating unclear with thread summaries

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#8719]
### Steps to reproduce

1. Run Nextcloud 27.1
2. Install the Mail app
3. ???
4. Enable thread summaries in Mail

### Expected behavior

I am aware of the ethics of the system

### Actual behavior

Data might leave the system, or might not leave the system. I depends on what text processing API implementation is installed.

* https://github.com/nextcloud/llm -> green?
* https://apps.nextcloud.com/apps/integration_openai with local ai -> yellow/green?
* https://apps.nextcloud.com/apps/integration_openai with openai -> red

### Mail app version

3.4

### PHP engine version

None

### Web server

None

### Database

None

### Additional info

Ref https://github.com/nextcloud/mail/issues/8508

**Comment by ChristophWurst** [comment]
@DaphneMuller @marcelklehr how was this solved/documented in other apps that use the new text processing APIs?

**Comment by ChristophWurst** [comment]
We could duplicate and merge https://github.com/nextcloud/llm/blob/c64b29e623dcbf3a6aeed1700e9bd5d693dd7aba/README.md#L20-L28 and https://github.com/nextcloud/integration_openai/blob/38cc3a1c09e3950be3222a8147e170ffc5e9045a/README.md#L15-L76 into this app's readme and app description but it's going to be very complex, long text and likely out of sync with the upstream rating at some point.

**Comment by ChristophWurst** [comment]
I've also created https://github.com/nextcloud/documentation/issues/10985 in case we want to explain the integration and implications of ethical AI in a more generic way and have the app docs link there.

**Comment by DaphneMuller** [comment]
We listed the multiple options and gave them multiple colours, for example, https://docs.nextcloud.com/server/latest/admin_manual/ai/index.html?highlight=ethi
![Screenshot 2023-08-24 at 18 40 58](https://github.com/nextcloud/mail/assets/86835268/a3ba649c-6500-4d71-9efe-25638a97c04c)
cal%20ai

**Comment by hamza221** [comment]
@DaphneMuller Should I add thread summaries to the table?

**Comment by marcelklehr** [comment]
@hamza221 I would maybe start a new list of downstream features that make use of the AI apps, as the thread summaries feature can be run using various apps in the backend with various Ethical AI Ratings.

**Comment by ChristophWurst** [comment]
> We listed the multiple options and gave them multiple colours, for example, [https://docs.nextcloud.com/server/latest/admin_manual/ai/index.html](https://docs.nextcloud.com/server/latest/admin_manual/ai/index.html?highlight=ethi)

I'm not sure I follow. Do you suggest to drop https://github.com/nextcloud/mail#ethical-ai-rating in favor of the rating in the docs and add the new summarize feature in the docs?

**Comment by marcelklehr** [comment]
The summarize feature is already present in the overview of AI features in the docs at [https://docs.nextcloud.com/server/latest/admin_manual/ai/index.html](https://docs.nextcloud.com/server/latest/admin_manual/ai/index.html?highlight=ethi) under "Text generation". In the mail app README I would suggest to mention the Ethical AI rating for important mail classification (since the implementation lives directly in the mail app) and mention that the mail app optionally makes use of the configured "Text processing" provider for Summaries with a link to the docs where all apps that provide a "Text processing" provider are listed.

Optionally, for completeness we could also add a new section of "downstream features" that make use of these APIs, like Talk Call transcription, E-Mail summaries etc.
