### ISSUE TITLE
Sort folders by number of unread messages

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#948]
We should sort folders by amount of unread count first, and then afterwards alphabetically. That way you have the relevant folders up top.

**Comment by ChristophWurst** [comment]
cc @nextcloud/mail 

:-1: from me. I prefer *sort by name*.

**Comment by jancborchardt** [comment]
cc @nextcloud/designers 

For reference, we already do not sort any of the other folders by name (Inbox, Sent, etc) cause alphabetic sorting makes little sense there.

If you have a bunch of folders, but only unread mails in the ones with S–Z or whatever, you always need to scroll down. This is quite annoying.

**How about an inbetween: We don’t sort by unread count, but we have "groups":**

- Regular folders (Inbox, Favorites, Drafts, Sent, Archive, Junk, Trash – in that order)
- Folders which have _any amount_ (over 0) of unread email, sorted A–Z
- Folders which have 0 unread email, sorted A–Z

**Comment by ChristophWurst** [comment]
> For reference, we already do not sort any of the other folders by name (Inbox, Sent, etc) cause alphabetic sorting makes little sense there.

We don't do that because there was a regression in one of the most recent releases. They were always sorted, but IIRC special folders were moved to the top.

**Comment by brrrrrrrt** [comment]
+1 for alphabetical ordering

sorting by unread, may be a nice **option**, but generally i think it is important to have a hierarchical and alphabetical structure, because if you have many folders with unread messages it is very likely you do this because you not want to read all those emails (think of maillinglists). to me it makes no sense that the folder with the most unread messages is the most important one. i have many folders with hundreds of unread messages. i get so many emails, my attention has to be focused on the important ones and not on the mailing-list with the highest traffic.

**Comment by jancborchardt** [comment]
@brrrrrrrt good arguments :+1: I'm convinced.
