### ISSUE TITLE
whups, ticket, helpdesk

### ISSUE THREAD

**Issue by alexhell** [nextcloud/mail#949]
### Feature Request

as this helpful plugin is based on Horde already, would it be difficult to integrats "whups" from horde? this is a ticket tracking software.

#### Summary

I miss a helpdesk functionallity in nextcloud. Would be nice to work mainly from nextcloud. This webmail app is a big step in this direction. If there would be a basic helpdesk, it would be awesome.

**Comment by ChristophWurst** [comment]
Hi and thanks for filing this feature request.

We currently focus purely on building a well-integrated IMAP client for Nextcloud. So that doesn't really fit into the scope of this app right now. Hence I'm closing this ticket.

You're right that we're using Horde libs. But there are numerous of those and we're just using the IMAP client libraries. If you're interested in building a helpdesk app for Nextcloud, I'm pretty sure that should be possible without interfering with this app if those are other Horde libraries. So I actually would recommend creating a new app for these features. We've even got a [developer manual](https://docs.nextcloud.com/server/13/developer_manual/) for Nextcloud (app) development, in case that you're interested in working on this.

Thanks! :)
