### ISSUE TITLE
Autoresponder not following out of office set globally

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#9984]
### Steps to reproduce

1. Set up provisioned accounts with Sieve
2. Set the autoresponder to follow the system settings
3. Configure an absence

### Expected behavior

The autoresponder is set automatically for the absence duration.

### Actual behavior

No autoresponder is set. A manual one can be set as workaround.

### Mail app version

4.0.0

### PHP engine version

None

### Web server

None

### Database

None

### Additional info

This is similar to https://github.com/nextcloud/server/issues/47058.

**Comment by st3iny** [comment]
I tested this and was only able to reproduce the bug when the cron job is triggered (at least one second) before the actual absence period starts. Then, the start date comparison to now fails and the autoresponder remains disabled.

https://github.com/nextcloud/mail/blob/c94f5e05373f275bedafe6e95df0f2a98e7ccbfb/lib/Listener/OutOfOfficeListener.php#L55

I'd propose to skip this condition if the event is an instance of `OutOfOfficeStartedEvent` and force enable the responder instead. Otherwise, the date check makes sense, e.g. in the case of the `OutOfOfficeChangedEvent` event.
